/* OxC3(Oxsomi core 3), a general framework and toolset for cross-platform applications.
*  Copyright (C) 2023 - 2026 Oxsomi / Nielsbishere (Niels Brunekreef)
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program. If not, see https://github.com/Oxsomi/core3/blob/main/LICENSE.
*  Be aware that GPL3 requires closed source products to be GPL3 too if released to the public.
*  To prevent this a separate license will have to be requested at contact@osomi.net for a premium;
*  This is called dual licensing.
*/

//types/math/flp.hpp
//
//GENERATED by src/tools/generate_hpp.py from include/types/math/flp.h - do not edit by hand.
//Re-run the generator (or `--check` in CI) after changing the C header.

#pragma once
#include <stdbool.h>
#include <stdint.h>
#include <assert.h>

namespace oxc {

	namespace c {
		#include "types/math/flp.h"
	}

	//Generated wrapper around the C EFloatType.
	//Queries over the packed EFloatType enum (exponent/mantissa widths, shifts, masks).
	//Pure arithmetic on the enum value, so this is a namespace like Time and ETextureFormat.
	namespace EFloatType {

		[[nodiscard]] inline c::Bool hasSign(c::EFloatType type) noexcept {
			return c::EFloatType_hasSign(type);
		}

		[[nodiscard]] inline c::U8 bytes(c::EFloatType type) noexcept {
			return c::EFloatType_bytes(type);
		}

		[[nodiscard]] inline c::U8 exponentBits(c::EFloatType type) noexcept {
			return c::EFloatType_exponentBits(type);
		}

		[[nodiscard]] inline c::U8 mantissaBits(c::EFloatType type) noexcept {
			return c::EFloatType_mantissaBits(type);
		}

		[[nodiscard]] inline c::U64 mantissaShift(c::EFloatType type) noexcept {
			return c::EFloatType_mantissaShift(type);
		}

		[[nodiscard]] inline c::U64 exponentShift(c::EFloatType type) noexcept {
			return c::EFloatType_exponentShift(type);
		}

		[[nodiscard]] inline c::U64 signShift(c::EFloatType type) noexcept {
			return c::EFloatType_signShift(type);
		}

		[[nodiscard]] inline c::U64 signMask(c::EFloatType type) noexcept {
			return c::EFloatType_signMask(type);
		}

		[[nodiscard]] inline c::U64 exponentMask(c::EFloatType type) noexcept {
			return c::EFloatType_exponentMask(type);
		}

		[[nodiscard]] inline c::U64 mantissaMask(c::EFloatType type) noexcept {
			return c::EFloatType_mantissaMask(type);
		}

		[[nodiscard]] inline c::Bool sign(c::EFloatType type, c::U64 v) noexcept {
			return c::EFloatType_sign(type, v);
		}

		[[nodiscard]] inline c::U64 abs(c::EFloatType type, c::U64 v) noexcept {
			return c::EFloatType_abs(type, v);
		}

		[[nodiscard]] inline c::U64 negate(c::EFloatType type, c::U64 v) noexcept {
			return c::EFloatType_negate(type, v);
		}

		[[nodiscard]] inline c::U64 exponent(c::EFloatType type, c::U64 v) noexcept {
			return c::EFloatType_exponent(type, v);
		}

		[[nodiscard]] inline c::U64 mantissa(c::EFloatType type, c::U64 v) noexcept {
			return c::EFloatType_mantissa(type, v);
		}

		[[nodiscard]] inline c::U64 isFinite(c::EFloatType type, c::U64 v) noexcept {
			return c::EFloatType_isFinite(type, v);
		}

		[[nodiscard]] inline c::U64 isDeN(c::EFloatType type, c::U64 v) noexcept {
			return c::EFloatType_isDeN(type, v);
		}

		[[nodiscard]] inline c::U64 isNaN(c::EFloatType type, c::U64 v) noexcept {
			return c::EFloatType_isNaN(type, v);
		}

		[[nodiscard]] inline c::U64 isInf(c::EFloatType type, c::U64 v) noexcept {
			return c::EFloatType_isInf(type, v);
		}

		[[nodiscard]] inline c::U64 isZero(c::EFloatType type, c::U64 v) noexcept {
			return c::EFloatType_isZero(type, v);
		}

		[[nodiscard]] inline c::U64 convert(c::EFloatType type, c::U64 v, c::EFloatType conversionType) noexcept {
			return c::EFloatType_convert(type, v, conversionType);
		}

	}
}
