/* OxC3(Oxsomi core 3), a general framework and toolset for cross-platform applications.
*  Copyright (C) 2023 - 2026 Oxsomi / Nielsbishere (Niels Brunekreef)
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program. If not, see https://github.com/Oxsomi/core3/blob/main/LICENSE.
*  Be aware that GPL3 requires closed source products to be GPL3 too if released to the public.
*  To prevent this a separate license will have to be requested at contact@osomi.net for a premium;
*  This is called dual licensing.
*/

#include "test_types_container_shared.h"
#include "types/base/mathi.h"
#include "types/math/vec4i.h"
#include "types/container/buffer_encrypt.h"
#include "types/container/string.h"

//Shared loop used for both AES256 and AES128 test vectors.
//Each test vector is: encrypt -> verify ciphertext + tag -> decrypt -> verify plaintext.

static void runAesVectors(
	Test *t,
	EBufferEncryptionType type,
	U64 count,
	const CharString *keys,
	const CharString *plainTexts,
	const CharString *aad,
	const U8 (*ivBytes)[13],
	const CharString *results
) {
	CharString tmp = CharString_createNull();
	Buffer full = Buffer_createNull();

	for (U64 i = 0; i < count; ++i) {

		//Copy plaintext and additional data into writable, 16-byte aligned buffers

		if (!Test_assert(t, "Encrypt: Copy plainText", CharString_createCopy(plainTexts[i], t->alloc, &tmp, &t->err)))
			goto clean;

		if (!Test_assert(t, "Encrypt: Copy aad", Buffer_createCopy(CharString_bufferConst(aad[i]), t->alloc, &full, &t->err)))
			goto clean;

		I32x4 iv  = I32x4_zero();
		I32x4 tag = I32x4_zero();

		Buffer_memcpy(Buffer_createRef(&iv, 12), Buffer_createRefConst(ivBytes[i], 12));

		Buffer target = CharString_buffer(tmp);

		BufferEncrypt encrypt = (BufferEncrypt) {
			.target         = (Buffer *restrict) &target,
			.additionalData = (const Buffer *restrict) &full,
			.type           = type,
			.flags          = EBufferEncryptionFlags_StopCreateIv,
			.nonConstEncrypt = {
				.key = (U32 *restrict) keys[i].ptr,
				.tag = (I32x4 *restrict) &tag,
				.iv  = (I32x4 *restrict) &iv
			}
		};

		if (!Test_assert(t, "Buffer_encryptAdvanced", Buffer_encryptAdvanced(&encrypt, &t->err)))
			goto clean;

		Test_assert(t, "Encrypt: size", CharString_length(tmp) + 16 == CharString_length(results[i]));

		I32x4 tmpTag = I32x4_load4(results[i].ptr + CharString_length(tmp));
		Test_assert(t, "Encrypt: tag", !I32x4_any(I32x4_neq(tag, tmpTag)));

		Test_assert(t, "Encrypt: ciphertext",
			Buffer_eq(
				Buffer_createRefConst(results[i].ptr, CharString_length(plainTexts[i])),
				CharString_bufferConst(tmp)
			)
		);

		//Decrypt and verify

		encrypt.flags = EBufferEncryptionFlags_None;

		if (!Test_assert(t, "Buffer_decryptAdvanced", Buffer_decryptAdvanced(&encrypt, &t->err)))
			goto clean;

		Test_assert(t, "Decrypt: plainText", !Buffer_neq(CharString_bufferConst(plainTexts[i]), CharString_bufferConst(tmp)));

	clean:
		Buffer_free(&full, t->alloc);
		CharString_free(&tmp, t->alloc);
	}
}

//These test vectors were generated by running the already verified AES scalar mode.
//These tests are mainly to ensure chunk sizes and various avx modes work correctly.
//If the crypto state (128-bit, 256-bit, 512-bit) isn't supported it'll skip the test.

static const U32 sizes[] = { 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536 };
static const U8  cryptoState[] = { 0, 1, 3 };
static const I64 blockSizeHints[] = { -1, -2, -4, -8, -16, 0 };

//Expected GMAC tags for each batch size (0 input, 0 key, 0 IV).
static const U32 tagForValidation[][4] = {
	{ 0xA7C8D1D0, 0xF06B9999, 0xB5985B26, 0x19B98AD4 },
	{ 0x4C08D3D1, 0x9F8AAA99, 0x833EBBDA, 0x5DC128EB },
	{ 0xD00C5C5D, 0x8A13B0C7, 0x27F268C8, 0x0BCD53D0 },
	{ 0xB35317AE, 0x7169FD46, 0x9AB60CD2, 0xBC48612D },
	{ 0x4CD7F570, 0xB30A6324, 0x6F6B090D, 0x82CC3C5E },
	{ 0x37CD8C39, 0x778FED25, 0xC6AFD548, 0xBE23CA56 },
	{ 0xA305D6CB, 0x5282B9E5, 0xFF840784, 0xC59FC7FD },
	{ 0x211B7D59, 0xF85C2DF1, 0x8E400234, 0x2121DF33 },
	{ 0x6AE4F202, 0x51459E9E, 0xAC94CD1D, 0xB6F9F124 },
	{ 0x1973CEC6, 0x8C9513DA, 0xBCB478BE, 0xCEDFE4BD },
	{ 0x41B37BB3, 0xE2227DFC, 0x3002BE12, 0xF07FD9E1 },
	{ 0x4FF4236F, 0x27610C8D, 0x4B17216F, 0xAD942BB3 },
	{ 0x292020BA, 0x2B8412E1, 0xF2532672, 0x77E10B40 }
};

//First 4 KiB of AES-256-GCM output (same key, same IV, encrypting all-zeros).
static const U32 validationData[][4] = {
	{ 0x3D40A7CE, 0x6E6B604D, 0xD3C54E07, 0x189DF3BA }, { 0xCA036072, 0x742AA637, 0x8EF5A2D1, 0x8E350675 },
	{ 0x28B14ADD, 0x7BE14A4D, 0x2459E841, 0xF7360C47 }, { 0xE1CB4147, 0x307FBB81, 0xE31D7C61, 0x1F3A0CAB },
	{ 0x738FC4D0, 0x372DA821, 0xE0AC9560, 0xA0679141 }, { 0xB049AFBC, 0x2DA6CEC0, 0x661CBCE6, 0xAD1D5E54 },
	{ 0xCD77FAAB, 0x24DA856E, 0xC5BDB05F, 0x29FC2CE5 }, { 0xABE10ABA, 0xF3E03728, 0x0EB78763, 0x12601793 },
	{ 0xBBC26243, 0xB1F4D866, 0x34E8FC37, 0x86D39C2C }, { 0x964214A1, 0xA86872E2, 0x37F50DE5, 0x79D505A8 },
	{ 0xBDEB21BB, 0x34ED57F3, 0x83B558BF, 0xCADD5071 }, { 0x5E2262F3, 0x70600A62, 0x29F55EAC, 0x662452FB },
	{ 0xC0788B76, 0x1EE5544B, 0xE507FAF5, 0xC65FA306 }, { 0x2410B7B0, 0xE126869C, 0x78D56AA9, 0x2EBED728 },
	{ 0x5AA09014, 0xBD43EE7C, 0xE3568BE9, 0x2601DC09 }, { 0x6EDFD64E, 0xC7BFC182, 0x53AD592A, 0x34E4C0A9 },
	{ 0x78526C7D, 0xA7407950, 0x93BAF6DE, 0x1EAFB6E8 }, { 0x76725346, 0x66C71B61, 0x7D585C95, 0x47A81B30 },
	{ 0xA7DDC9AC, 0x2C8E438A, 0x14D5690A, 0xD3724C74 }, { 0x9B6B324F, 0x8642F37E, 0xA7F80ECA, 0xBE6EE0EA },
	{ 0x72539C66, 0xCB2D4012, 0x9DE9EA5F, 0xA7F4C776 }, { 0x9CB7BD6A, 0x38A0FA0D, 0x2C28E2A0, 0x8BD40E73 },
	{ 0x2FAC9D86, 0x3ECF8E16, 0x1FE610A6, 0x8E2C51AC }, { 0x068CFB95, 0x76BC62DE, 0x35515569, 0x4C86DB8A },
	{ 0x14F968C2, 0xAAB39AB4, 0xB2FDED20, 0x817972D1 }, { 0xD8B3B437, 0x2275D1DD, 0xE4BF2CEB, 0x9FCF47DC },
	{ 0xCD1CFAB0, 0x56DBDE23, 0x0AF5D193, 0xE7DEEDE4 }, { 0xF7B02008, 0x0873E0C6, 0xFD1D2D9E, 0x326CB097 },
	{ 0xD83600A5, 0x34BF4D28, 0xE02E2968, 0x7CC82EB6 }, { 0xEBB17C88, 0x2067B476, 0xDB304110, 0x876396F1 },
	{ 0x3FC42D48, 0x25EF8823, 0xE14441D2, 0x4E83BD44 }, { 0xA37D8E44, 0xF9EAA6BF, 0x5C21DABC, 0xF30C50BA },
	{ 0x32B45CB9, 0x9F1295D1, 0x875F94C3, 0xA42C86D1 }, { 0xF18FEAD6, 0xDC341020, 0xF58F324D, 0x09A973FD },
	{ 0x79D33462, 0x9CBFCFE4, 0x9A58F636, 0x8AE92C8A }, { 0x71D9E45F, 0xC515BC03, 0x331D02C4, 0x2B93C196 },
	{ 0x14365037, 0x9DF6CA1A, 0x79B7033F, 0x031AE6C9 }, { 0xEAD7521F, 0x5CDD6D9C, 0xCE182286, 0x1AA1E787 },
	{ 0x7A750519, 0x530AE0FC, 0x294FF449, 0xB570CCCB }, { 0x55EAFEB9, 0xE8CE4252, 0x856BE53C, 0x7216B880 },
	{ 0xCCECBEC6, 0x56ADA0BC, 0xE8CE9623, 0x407F5478 }, { 0x9B0808EB, 0x5167A5E6, 0x467E1E78, 0x56F82C1E },
	{ 0x9135C13B, 0x02424A49, 0xD79404D2, 0x9A4587AD }, { 0xB6557575, 0xC14C2842, 0x0785471F, 0xFF5DC9F5 },
	{ 0xD78DFF35, 0xED5747CE, 0x8CF811AE, 0x48501BDE }, { 0x99660EC2, 0x95066BA2, 0xB47916CD, 0x6F64225A },
	{ 0x31111D96, 0xD9685C12, 0x2EE31393, 0x2457A84A }, { 0xC17EDCA1, 0xFE29FACF, 0x82839672, 0xF3EEA81C },
	{ 0x281C3BBF, 0x6CFBC239, 0x3F4976ED, 0x2EA622FA }, { 0x2A1C9B78, 0x53CBE096, 0xEBEEECFD, 0xC6E1C78D },
	{ 0x3DBF755C, 0x33832152, 0xD6E46D90, 0x2244C67D }, { 0xF40F59E5, 0x30EC02AC, 0x67ACA9E4, 0xE9B2CA59 },
	{ 0xF3D2214A, 0x576E618F, 0xE84EB5A3, 0xAA0A7302 }, { 0x4D633C2F, 0x6CFC1771, 0x056FAC01, 0x0CD29E5A },
	{ 0x2A4E8C95, 0xF099B6C2, 0xB3147C0C, 0x4196BD02 }, { 0xFC56AD95, 0x602F729C, 0x91AFA17D, 0xCBDBE023 },
	{ 0x2BE1930E, 0x1D79B264, 0x76240D44, 0xDDA88ED8 }, { 0x58A66546, 0x18C44674, 0x74A77798, 0x7E402656 },
	{ 0x46BD637F, 0xD8DBD232, 0x4A0F79BC, 0x39722B77 }, { 0x26288B6F, 0x09F67F67, 0x112CC80D, 0x54E3FFA3 },
	{ 0xA653AC2E, 0x099E1396, 0xBC0DFD8A, 0x37424D2A }, { 0xC768A356, 0xE42543A3, 0x8791CEAD, 0x7EEAE832 },
	{ 0x78A6AB60, 0x8D6006A5, 0x6D964508, 0x90F7B529 }, { 0x5E1BAC18, 0x68B8BE94, 0xFD5B3888, 0x606A321E },
	{ 0xFAF76439, 0xB6297A68, 0x8BAFB36E, 0x3A7AFDAB }, { 0x10DE908C, 0x0F5E06D9, 0xF01B4FE0, 0x2EAC3BD3 },
	{ 0x384885E6, 0xC4488A09, 0x89FFA1F7, 0x039657CE }, { 0xDDD08C1F, 0x61C39606, 0xCB49164B, 0x08049613 },
	{ 0xF1FEF262, 0xF0021A1A, 0x00C70C38, 0x32248ABA }, { 0x31A60C7F, 0xA89AE6BF, 0xFD5239A9, 0x174F5CD0 },
	{ 0x58D78236, 0xA9C9FA10, 0xD51D8E10, 0x90D46EAF }, { 0x60391380, 0xCC3FF07B, 0x99D40106, 0x1032FBEC },
	{ 0x69BBE004, 0x5A0096AD, 0xE6BEA7B3, 0x77C5BBB1 }, { 0x014374A5, 0xFA6485B6, 0x62015EFE, 0x5E3E5B14 },
	{ 0xC0D3365F, 0x342EE51B, 0x18A21292, 0x3C7D65AE }, { 0x4CB9026C, 0xBAFD0BB1, 0x615481D5, 0xBFE5FA90 },
	{ 0xC2B5DB6D, 0x3CB75207, 0xF32F73BA, 0xF538D4FA }, { 0xBCB378E5, 0x33877D4F, 0xC253A365, 0x54162534 },
	{ 0xAC6C76C8, 0x85F85B74, 0x770E1F9B, 0x49550506 }, { 0x9693F06C, 0xE5AC4EE3, 0xDB98AB2E, 0xFC7014ED },
	{ 0xC939C8F8, 0x3F26E58D, 0xD2BC9E15, 0x173C4424 }, { 0xEDE1132F, 0xF123346D, 0x2F4A17D7, 0x58714B31 },
	{ 0x5A9D9C1E, 0x6321A3C7, 0xD9D3C98D, 0xA8900C04 }, { 0xE6CA5DE1, 0x09E17928, 0x6860E5E9, 0x1ECF4494 },
	{ 0xC89D694F, 0xFC45E16F, 0x314414AF, 0xA808D2AD }, { 0x12359149, 0x8923EA91, 0x15EBD6EE, 0x75ACEBA5 },
	{ 0xE067A3E8, 0x6345128D, 0x4E0D2D34, 0xC5CD3202 }, { 0xFC6C0D73, 0x31033383, 0x1F507894, 0xE922E9BC },
	{ 0x78767787, 0x9263BEB4, 0x9AB04EAC, 0xF12AA402 }, { 0x8331873E, 0xEE167032, 0x0456BCE3, 0xC0D9D1AE },
	{ 0x95BD258F, 0x4F9C8362, 0x32774CC5, 0x31FE216B }, { 0x292F9D4E, 0x6B3C2A11, 0xB0A21C32, 0xF8ABE027 },
	{ 0xE1463080, 0xCD362CEA, 0x37EA68F4, 0x84E979DE }, { 0x66F12804, 0x8A35382A, 0xC86F40AF, 0x6C5D9DB2 },
	{ 0x74567861, 0x1DF9843C, 0xE9FEF9B2, 0x24A62F0E }, { 0x4537A00C, 0xFC97BE14, 0x9FD7CDEF, 0x025B8D1E },
	{ 0x1EC6E44A, 0xEC1DF2A6, 0x21DE0DC9, 0x287E0CC9 }, { 0x39E398A4, 0xC93744FA, 0xAA9C2154, 0x68774C38 },
	{ 0xA587AFDA, 0x76020248, 0x0348D4A8, 0xD7FBA797 }, { 0x04306E27, 0x2ED0BAB7, 0xA5713553, 0x351B5D18 },
	{ 0x30A6F627, 0xCFD3E28B, 0x2D7497A7, 0x9F262214 }, { 0x8866703B, 0x4D709B42, 0xC9E7CC39, 0x8E0B0BD0 },
	{ 0xCBCFFDA0, 0xAE767FDC, 0x4CEBF0E3, 0xDCCAC538 }, { 0x501E7D40, 0x4B08C29D, 0x7256A4C4, 0x6C56A6F6 },
	{ 0x9D61A89C, 0x1C562D3E, 0x24EAF4B9, 0x303A5D8E }, { 0x198D8945, 0x12952D5D, 0x4AA93827, 0xD7A3D8A0 },
	{ 0x3E3960CD, 0x32764DC6, 0x489E8AA4, 0x435EFD8A }, { 0xB9E43C08, 0x80F72057, 0x565E3542, 0x1E3EFEFC },
	{ 0x443F06A0, 0x1B7ABE91, 0xAF01B313, 0x1A7C7B6B }, { 0x74B83334, 0x3C47F405, 0x9757156D, 0x98170850 },
	{ 0x3FFC8530, 0x480A70A8, 0x37339E9F, 0xC53BC6BB }, { 0x9148A60E, 0x5DBB12EF, 0xE1F8889E, 0xAFC7CB3B },
	{ 0x1E5DA806, 0x18AA03B7, 0x303FFE69, 0x36C14DB4 }, { 0x1E743D82, 0x6E97FF6F, 0xE3523E30, 0x8EB81EBB },
	{ 0x1FD04F18, 0xA1062BD4, 0xD2E53D2B, 0x61C1B87B }, { 0x479078BB, 0xC81E56F8, 0x899CAC82, 0x154D17B1 },
	{ 0x75B2DC86, 0x16928D6E, 0x17871DAE, 0xABDBE683 }, { 0x051A8403, 0x73EAD8FF, 0x4E436399, 0x877F53B1 },
	{ 0x0ED879F7, 0x0A156F56, 0xC553D390, 0x91603295 }, { 0x89982A9C, 0x642A292A, 0x177C429C, 0xC7C06E09 },
	{ 0x675B92E9, 0x2C8551C3, 0x92DD2BC4, 0xE416DD84 }, { 0x15C289D2, 0x0150CAE0, 0x2796350C, 0xBDFAA784 },
	{ 0xEE0B0D0E, 0x36F9E2A3, 0x436E82DA, 0x08632837 }, { 0x0D16616B, 0xF32FECB2, 0x9546B16F, 0xDDB6F833 },
	{ 0x4F4ECD5D, 0xECF9F5E5, 0x0891D2AE, 0xC0BD3242 }, { 0x2378C8CA, 0xED0DEDC4, 0xAF92FE6F, 0xFD6FA5E6 },
	{ 0x8DAD4DB1, 0xF453913D, 0x1A3A0D6C, 0x057A3CD6 }, { 0xC60B1AB8, 0x9D03A399, 0x01FB2F19, 0x4AB9C12A },
	{ 0x635DA6B0, 0xE62CDFD3, 0xCFE71FA2, 0xD167B8DB }, { 0xA590598F, 0xC783D126, 0xB6708D4A, 0xB2B0ECBF },
	{ 0x5D3F8913, 0x0A4936B0, 0x079B839E, 0xFD3AC7AA }, { 0xB55F76B3, 0x320619A9, 0x85E0ABA1, 0xE5F0C581 },
	{ 0xB3D39CC5, 0x721A2C4E, 0x369BEF25, 0xC94FAC26 }, { 0x6E666FA7, 0x3ED27274, 0x1B2C87F4, 0x84FF2224 },
	{ 0x4B92248A, 0x84AF1A93, 0x077C08B4, 0x97EBB986 }, { 0xD0D00A51, 0xEB32F0CA, 0x3CE48B33, 0xCBAE3265 },
	{ 0xF299FAFE, 0x023BDE52, 0xF00CFEEA, 0xFBC5BDB8 }, { 0x466D15EB, 0xC1143A76, 0xCC91E945, 0x113788C1 },
	{ 0xEBE9A336, 0xB36CF1AE, 0x7A9ED307, 0x9CD5143B }, { 0xAFA33137, 0x183BE4AE, 0x0724EB14, 0xF9980AB4 },
	{ 0x77B383E7, 0xD330B55C, 0xD26B6955, 0xA6B15733 }, { 0xE068AEE0, 0xF8E2A40E, 0x25EAB1B8, 0xFC53E995 },
	{ 0x51970AFE, 0xE2063C58, 0xCE09C9BB, 0xE5116509 }, { 0xBEAC6A33, 0x4D56FD55, 0xAA9DC707, 0x8A7ECF32 },
	{ 0xEBF1D829, 0xD0FFD041, 0x75B5B4C1, 0x243049A4 }, { 0xC23410FE, 0x9E67F752, 0xD0D38DC8, 0x58B44753 },
	{ 0x13B59636, 0xF3CAFDDB, 0xA8E2B607, 0x8A010939 }, { 0xF5A2D405, 0x33547CCE, 0x3D0640BA, 0xDC315FAA },
	{ 0xEB2F3CB0, 0x8096F9DA, 0x3D18EE25, 0x3E2B1B8B }, { 0x6E929DDE, 0x367D44F7, 0xD7147CE1, 0xFD4FB868 },
	{ 0xE9F5F88F, 0x9D529001, 0xB6DBC94D, 0x3639FB7E }, { 0xC0FD0A16, 0x6073AC46, 0x39016027, 0x14BB5C66 },
	{ 0x2E056C31, 0xFDE62DD5, 0xE9137B05, 0xF9D1019F }, { 0xB5FC5D2D, 0xFCB65D78, 0x1643F451, 0xF3D1A0B4 },
	{ 0x369D0A22, 0x92461B58, 0x72B8BB6D, 0xF51C2BB0 }, { 0x2FBF9F31, 0xAD6A3F6D, 0xFEAA25EB, 0x4580A87A },
	{ 0x2244E42C, 0x224E3899, 0xD9F72707, 0x4764084C }, { 0x9BB3D472, 0x2C6C3F12, 0xE875990E, 0x2C2EB3FC },
	{ 0x4634E767, 0x7F22FE1B, 0xFADBAF9E, 0xBF1BF5BF }, { 0x3631AD69, 0x81F3C0B9, 0x2A2DAF62, 0x3C36472D },
	{ 0x702F4057, 0x9DEDC83A, 0x5E46F49A, 0x12AF152D }, { 0x2B924C21, 0xF1C39F61, 0xD8296B05, 0x9D54B1CC },
	{ 0x4F124B25, 0xF6B4EEAE, 0xC565BF19, 0x8EEA03F1 }, { 0x3B517593, 0x7574DEA0, 0x1D6AEAE6, 0x008B35FD },
	{ 0xFE83EE0E, 0x5A199109, 0x79DAA261, 0x6F95A49A }, { 0x31E9FF6C, 0xBC535A5E, 0x8C0D71B5, 0xDFFEFE30 },
	{ 0x153B3CEB, 0xAE5AAE21, 0x74202E1E, 0xFFB99596 }, { 0x99696E18, 0x3CB58DF5, 0x51B028E5, 0x23C29CB2 },
	{ 0x62566887, 0x6835926D, 0x9784A277, 0xE2E2275C }, { 0x155C07A9, 0x3E28FAFD, 0xE9E23209, 0xAAB0D284 },
	{ 0x9A36AFBE, 0x3C96CBAC, 0xDCF707AA, 0x46E599E1 }, { 0x5A6077D4, 0x3342D996, 0x242C9CB2, 0xD7E9F35E },
	{ 0x004FD7BD, 0x10C41D0C, 0xBDA8BCD9, 0xF47FFF7D }, { 0x7EB7CBAF, 0xF4E0444E, 0x5D4FEFF0, 0x79B60B4B },
	{ 0xE9B32153, 0x3B63908B, 0xD58F3649, 0x30BD19D4 }, { 0x99ED9104, 0x4B8860DA, 0x44B8248B, 0xB77B4B2C },
	{ 0xCF67DB6C, 0x1C99D893, 0x915B4371, 0xF93BE261 }, { 0x3A07D570, 0x89A38DD8, 0x7D238416, 0x873E2114 },
	{ 0xBE256913, 0xBB68A43B, 0x8AC3D201, 0x69C27E3C }, { 0x2C05FE81, 0xBC70EFD7, 0xB9A98970, 0x9D0B6063 },
	{ 0xDA816DF8, 0x3F43D48D, 0x1D5623D5, 0x04D0507D }, { 0xB5067867, 0x14606B1F, 0xFE2338F6, 0x151300B7 },
	{ 0xCD46F2AF, 0x6DEA4520, 0x538A3CC4, 0xC725AE88 }, { 0xB2670294, 0x62B59855, 0x44B8346F, 0xF0B3CB20 },
	{ 0x8F8BFD86, 0xF014C0C3, 0x27242A65, 0xCB95AD7D }, { 0x390F0D40, 0x50AB6884, 0x8D71477A, 0x0C37FF16 },
	{ 0x5969BB2E, 0x197D96A0, 0x6A1EDFA1, 0x9F64C164 }, { 0xEEC95FEC, 0x1F252B19, 0x48BDBC4A, 0x3F1C9B2E },
	{ 0xFB037139, 0x51FB073B, 0x290537F4, 0x46474D5C }, { 0x79468BD5, 0x0E4BE9D1, 0x366BF5A6, 0x7332E48D },
	{ 0x301F2E7D, 0x017CA33B, 0x9E09AC7E, 0x33E90588 }, { 0x5BA29461, 0x35217E9F, 0x3FE7D7A2, 0x26EA1207 },
	{ 0xB2844FE6, 0x8DA250E1, 0xD3382EA4, 0xD6540EBA }, { 0xD169A76E, 0x1ECBBBA9, 0x820C8640, 0x0C15329E },
	{ 0x5F15F369, 0xAD20914F, 0x8F013F5A, 0x5F35192A }, { 0x7D39A3F5, 0xA8A3EE0E, 0x69EC2ACA, 0xBFFA9AFC },
	{ 0xFD44D0EB, 0xFE40AA10, 0xDBDE0F35, 0x83F565A3 }, { 0x6372B75F, 0x75537B31, 0xE2BEBA39, 0x2D46D5FC },
	{ 0x21C4F4AD, 0x900B5064, 0x3C3C7269, 0x1A4C1AE4 }, { 0x9135F662, 0x761AAB42, 0x2EBD1C4C, 0x8D76B267 },
	{ 0xFD084277, 0x5DA21B4D, 0xD362360A, 0xB2E3CE48 }, { 0x285B0D3C, 0xB4E95A53, 0xF41D54F0, 0x8BC56687 },
	{ 0x22BE70D2, 0xA22FA394, 0xB5CDD635, 0x998574DE }, { 0x7FCD9548, 0xB235C426, 0x9C9657D6, 0x00CBF3D2 },
	{ 0x42AA6CD3, 0x460CD99A, 0xC9A7F054, 0x6C1D2CC6 }, { 0x2ED886D3, 0x6ED67A8D, 0x6B9357AE, 0x6DE8C23D },
	{ 0x5FF1C32E, 0xA404F936, 0xD8FC85B3, 0x0942EA9C }, { 0xCB967BA7, 0xC6A0E8BE, 0x0E5B5F61, 0xE5924A76 },
	{ 0x74D6A2BC, 0x4DE696E3, 0xE07E4400, 0x5915C55F }, { 0x71A2D997, 0x34A03F65, 0x8CEBA888, 0x9F77621B },
	{ 0x0FEBB9B1, 0x7F10C47F, 0x77476C17, 0x36B23A4C }, { 0x5B194EFF, 0xE082F14B, 0xF9B9B2A8, 0x49E36E7A },
	{ 0x0E8F15A2, 0x3D7B8A5B, 0xC26E4912, 0x8061467C }, { 0xFE78DBD4, 0xDC05FA09, 0xAE0812A9, 0x57B269C9 },
	{ 0xF2768C87, 0xC72FDF03, 0x1E8D7C50, 0x810BCCBD }, { 0xD4781DFE, 0x16E6E8AA, 0x0095622D, 0x4FC550A3 },
	{ 0x55D6A937, 0x775671F1, 0xF6C80B8B, 0xC70953C0 }, { 0xBCCCF009, 0x8F0FB3D7, 0x55E19DDA, 0x45BD55AA },
	{ 0x566C30A8, 0x8DDF9EBA, 0x20172A13, 0x497D2877 }, { 0xB8126478, 0x1D5E15C3, 0xF763324E, 0xB92B8C84 },
	{ 0x8476D9F9, 0x59817933, 0xD6E9A593, 0xD9722151 }, { 0xE0066E60, 0xCE84E243, 0x77C32CE2, 0x9E442D82 },
	{ 0x4549D8F4, 0xD781D113, 0xCE4FC990, 0x65FD9D95 }, { 0xB77832BD, 0xB096EDF4, 0x83B3BF86, 0x201CFA1B },
	{ 0x34873483, 0x54E474C6, 0x4E7F2AC1, 0x8D9D62ED }, { 0x586386B4, 0xDFD7B871, 0xA438E302, 0xD00897F2 },
	{ 0xF1D1B8D4, 0x77300FFE, 0x7A0A7244, 0x511E59EE }, { 0x7F7A01E8, 0xF1FF1E4D, 0x533AC81F, 0x64EA3A68 },
	{ 0xB9FADA62, 0xF63F5EE9, 0xFF09E326, 0xB0940362 }, { 0xE870675E, 0x21BB85BF, 0x4CC992D8, 0x02959DFA },
	{ 0x46D93039, 0x6F8A7149, 0xF7C2E6B5, 0xCE4F0A85 }, { 0x1F58D811, 0x70DE3562, 0x12CA165C, 0x740F496A },
	{ 0xC43381B6, 0xD2657A98, 0x07EEF624, 0x37EBED49 }, { 0xA736E336, 0xE6FCF236, 0x4D6E9B8E, 0x8D6CF6BE },
	{ 0xDC3770C0, 0x2257C8C6, 0xA20C5027, 0xB589E5EA }, { 0xFA9D25D1, 0x28A9CD8A, 0x76F934A7, 0x642A2CD2 },
	{ 0xBA14B1E4, 0xB07997DD, 0xAA21715D, 0xA952E481 }, { 0x48C3220F, 0x562B3DBE, 0x58EA4011, 0x452AC2AD },
	{ 0x2364099B, 0xC1E2C71D, 0xDA1BD11B, 0x221AFCA9 }, { 0x066FC8EB, 0xFA355FB8, 0x8166ED98, 0x1AED010B },
	{ 0xA6ABA99A, 0xBFAB476F, 0xA84EEE81, 0x2B2524B2 }, { 0xE5A08A38, 0x585F7862, 0x0184F9D0, 0x9D937BF0 },
	{ 0x8AA95323, 0x664AC0EF, 0x1D7B4C8E, 0x4DD0BAC6 }, { 0x6D5FA869, 0xD3CE722F, 0xE5C0B004, 0x01F9EFCB },
	{ 0x8FE96FE8, 0x31403108, 0x1C9CE4EE, 0xB9371C50 }, { 0xE0297F9A, 0xFE5EE40E, 0x4FB08516, 0x3700DB8D },
	{ 0xC2748E78, 0xE10923BF, 0x8E7E644A, 0x00762329 }, { 0x1C95E876, 0x422A8C0A, 0xAC58CA22, 0xE8724F5D },
	{ 0x1B6D6C14, 0x039F14E4, 0x845F0EE2, 0x8FEA05E9 }, { 0xAC2AF775, 0x1270E94F, 0xBA053E67, 0x992056C1 },
	{ 0x7ADB8880, 0xCD220B50, 0xD1C8232D, 0x14438B90 }, { 0x8A5C69AE, 0x74E9BA49, 0xA2622A71, 0x86DF1414 },
	{ 0x5D514CA6, 0x9EC3CC9A, 0x1424E5CD, 0xF65B8E68 }, { 0xC6064F4D, 0x03297CF1, 0xB250C7AB, 0x342EDA8E },
	{ 0x50D2E9C7, 0xD4328699, 0x42623544, 0x8D0504EF }, { 0x8E3CAF4C, 0x48F2B9BE, 0xD70372D6, 0xEE7E438A }
};

static Bool aesCreateCtx(
	Test *t, const C8 *label,
	I64 blockSizeHint, U8 cryptoSt,
	AESEncryptionKey key, AESEncryptionContext *ctx,
	U8 *blockSizeMax, U8 *use256Or512
) {
	if (!Buffer_aesExpertCreate(
		I32x4_zero(),
		EBufferEncryptionType_AES256GCM,
		key,
		blockSizeHint,
		0,
		cryptoSt,
		blockSizeMax,
		use256Or512,
		ctx,
		&t->err
	)) {
		Test_assert(t, label, false);
		return false;
	}

	return true;
}

void Test_aesValidation(Test *t) {

	Test_setModule(t, "aes256gcm validate batch sizes, crypto capabilities");

	const AESEncryptionKey key = { 0 };

	Buffer full = Buffer_createNull();

	if (!Buffer_createUninitializedBytes(65536 * 2, t->alloc, &full, &t->err)) {
		Test_assert(t, "Alloc full buffer", false);
		return;
	}

	Buffer_unsetAllBits(full, &t->err);

	for (U64 l = 0; l < sizeof(cryptoState) / sizeof(cryptoState[0]); ++l) {

		AESEncryptionContext ctx = { 0 };
		U8 blockSizeMax = 0, use256Or512 = 0;

		//Check whether this variant is supported
		if (!aesCreateCtx(t, "aesCreateCtx test", -16, cryptoState[l], key, &ctx, &blockSizeMax, &use256Or512))
			continue;

		if (use256Or512 != cryptoState[l])		//Hardware doesn't support this
			continue;

		for (U64 i = 0; i < sizeof(sizes) / sizeof(sizes[0]); ++i) {

			const U64    siz        = sizes[i];
			Buffer       unit       = Buffer_createRef(full.ptrNonConst, siz);
			const I32x4  tagExpect  = I32x4_load4((const void*)&tagForValidation[i]);

			//Encrypt

			if (!aesCreateCtx(t, "Enc aesCreateCtx", -16, cryptoState[l], key, &ctx, &blockSizeMax, &use256Or512))
				continue;

			Buffer_unsetAllBits(unit, &t->err);
			Buffer_aesExpertEncUpdate(&ctx, unit, 0, blockSizeMax, use256Or512);
			Buffer_aesExpertFinalize(&ctx, 0, siz, I32x4_zero());

			Test_assert(t, "Enc GMAC", !I32x4_neq4(ctx.tag, tagExpect));

			//Check first 4 KiB of ciphertext output matches precomputed reference.
			//(Tags and decrypt already cover the full range; this is an extra check in case AES fails but ghash succeeds)

			const Buffer ref  = Buffer_createRefConst(validationData, U64_min(sizeof(validationData), siz));
			const Buffer got  = Buffer_createRefConst(full.ptr,       U64_min(sizeof(validationData), siz));
			Test_assert(t, "Enc ciphertext", !Buffer_neq(got, ref));

			//Check AAD

			if (!aesCreateCtx(t, "AAD create", -16, cryptoState[l], key, &ctx, &blockSizeMax, &use256Or512))
				continue;

			Buffer_aesExpertUpdateAAD(&ctx, unit, blockSizeMax, use256Or512);
			Test_assert(t, "AAD GMAC", Buffer_aesExpertFinalize(&ctx, 0, siz, tagExpect));

			//Decrypt

			if (!aesCreateCtx(t, "Dec create", -16, cryptoState[l], key, &ctx, &blockSizeMax, &use256Or512))
				continue;

			Buffer_aesExpertDecUpdate(&ctx, unit, 0, blockSizeMax, use256Or512);
			Test_assert(t, "Dec GMAC", Buffer_aesExpertFinalize(&ctx, 0, siz, tagExpect));

			//Decrypting all-zeros with the same key/IV should yield all-zeros back

			Buffer zeroBuf = Buffer_createRef(full.ptrNonConst + siz, siz);
			Buffer_unsetAllBits(zeroBuf, &t->err);
			Test_assert(t, "Dec round-trip", !Buffer_neq(unit, zeroBuf));
		}
	}

	Buffer_free(&full, t->alloc);
}

//Test vectors 13-16: https://luca-giuzzi.unibs.it/corsi/Support/papers-cryptography/gcm-spec.pdf
//Test vectors 2.1.2 – 2.8.2: https://www.ieee802.org/1/files/public/docs2011/bn-randall-test-vectors-0511-v1.pdf

void Test_aes256gcm(Test *t) {

	Test_setModule(t, "aes256gcm");

	const CharString keys[] = {

		CharString_createRefSizedConst(
			"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
			"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
			32, true),

		CharString_createRefSizedConst(
			"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
			"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
			32, true),

		CharString_createRefSizedConst(
			"\xFE\xFF\xE9\x92\x86\x65\x73\x1C\x6D\x6A\x8F\x94\x67\x30\x83\x08"
			"\xFE\xFF\xE9\x92\x86\x65\x73\x1C\x6D\x6A\x8F\x94\x67\x30\x83\x08",
			32, true),

		CharString_createRefSizedConst(
			"\xFE\xFF\xE9\x92\x86\x65\x73\x1C\x6D\x6A\x8F\x94\x67\x30\x83\x08"
			"\xFE\xFF\xE9\x92\x86\x65\x73\x1C\x6D\x6A\x8F\x94\x67\x30\x83\x08",
			32, true),

		CharString_createRefSizedConst(
			"\xE3\xC0\x8A\x8F\x06\xC6\xE3\xAD\x95\xA7\x05\x57\xB2\x3F\x75\x48"
			"\x3C\xE3\x30\x21\xA9\xC7\x2B\x70\x25\x66\x62\x04\xC6\x9C\x0B\x72",
			32, true),

		CharString_createRefSizedConst(
			"\xE3\xC0\x8A\x8F\x06\xC6\xE3\xAD\x95\xA7\x05\x57\xB2\x3F\x75\x48"
			"\x3C\xE3\x30\x21\xA9\xC7\x2B\x70\x25\x66\x62\x04\xC6\x9C\x0B\x72",
			32, true),

		CharString_createRefSizedConst(
			"\x69\x1D\x3E\xE9\x09\xD7\xF5\x41\x67\xFD\x1C\xA0\xB5\xD7\x69\x08"
			"\x1F\x2B\xDE\x1A\xEE\x65\x5F\xDB\xAB\x80\xBD\x52\x95\xAE\x6B\xE7",
			32, true),

		CharString_createRefSizedConst(
			"\x69\x1D\x3E\xE9\x09\xD7\xF5\x41\x67\xFD\x1C\xA0\xB5\xD7\x69\x08"
			"\x1F\x2B\xDE\x1A\xEE\x65\x5F\xDB\xAB\x80\xBD\x52\x95\xAE\x6B\xE7",
			32, true),

		CharString_createRefSizedConst(
			"\x83\xC0\x93\xB5\x8D\xE7\xFF\xE1\xC0\xDA\x92\x6A\xC4\x3F\xB3\x60"
			"\x9A\xC1\xC8\x0F\xEE\x1B\x62\x44\x97\xEF\x94\x2E\x2F\x79\xA8\x23",
			32, true),

		CharString_createRefSizedConst(
			"\x83\xC0\x93\xB5\x8D\xE7\xFF\xE1\xC0\xDA\x92\x6A\xC4\x3F\xB3\x60"
			"\x9A\xC1\xC8\x0F\xEE\x1B\x62\x44\x97\xEF\x94\x2E\x2F\x79\xA8\x23",
			32, true),

		CharString_createRefSizedConst(
			"\x4C\x97\x3D\xBC\x73\x64\x62\x16\x74\xF8\xB5\xB8\x9E\x5C\x15\x51"
			"\x1F\xCE\xD9\x21\x64\x90\xFB\x1C\x1A\x2C\xAA\x0F\xFE\x04\x07\xE5",
			32, true),

		CharString_createRefSizedConst(
			"\x4C\x97\x3D\xBC\x73\x64\x62\x16\x74\xF8\xB5\xB8\x9E\x5C\x15\x51"
			"\x1F\xCE\xD9\x21\x64\x90\xFB\x1C\x1A\x2C\xAA\x0F\xFE\x04\x07\xE5",
			32, true),
	};

	const CharString plainTexts[] = {

		CharString_createNull(),

		CharString_createRefSizedConst(
			"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
			16, true),

		CharString_createRefSizedConst(
			"\xD9\x31\x32\x25\xF8\x84\x06\xE5\xA5\x59\x09\xC5\xAF\xF5\x26\x9A"
			"\x86\xA7\xA9\x53\x15\x34\xF7\xDA\x2E\x4C\x30\x3D\x8A\x31\x8A\x72"
			"\x1C\x3C\x0C\x95\x95\x68\x09\x53\x2F\xCF\x0E\x24\x49\xA6\xB5\x25"
			"\xB1\x6A\xED\xF5\xAA\x0D\xE6\x57\xBA\x63\x7B\x39\x1A\xAF\xD2\x55",
			64, true),

		CharString_createRefSizedConst(
			"\xD9\x31\x32\x25\xF8\x84\x06\xE5\xA5\x59\x09\xC5\xAF\xF5\x26\x9A"
			"\x86\xA7\xA9\x53\x15\x34\xF7\xDA\x2E\x4C\x30\x3D\x8A\x31\x8A\x72"
			"\x1C\x3C\x0C\x95\x95\x68\x09\x53\x2F\xCF\x0E\x24\x49\xA6\xB5\x25"
			"\xB1\x6A\xED\xF5\xAA\x0D\xE6\x57\xBA\x63\x7B\x39",
			60, true),

		CharString_createNull(),

		CharString_createRefSizedConst(
			"\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C"
			"\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C"
			"\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3A\x00\x02",
			48, true),

		CharString_createNull(),

		CharString_createRefSizedConst(
			"\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C"
			"\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C"
			"\x2D\x2E\x2F\x30\x31\x32\x33\x34\x00\x04",
			42, true),

		CharString_createNull(),

		CharString_createRefSizedConst(
			"\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C"
			"\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C"
			"\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3A\x3B\x00"
			"\x06",
			49, true),

		CharString_createNull(),

		CharString_createRefSizedConst(
			"\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C"
			"\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C"
			"\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3A\x3B\x3C"
			"\x3D\x3E\x3F\x40\x41\x42\x43\x44\x45\x46\x47\x48\x49\x00\x08",
			63, true),
	};

	const CharString aad[] = {

		CharString_createNull(),
		CharString_createNull(),
		CharString_createNull(),

		CharString_createRefSizedConst(
			"\xFE\xED\xFA\xCE\xDE\xAD\xBE\xEF\xFE\xED\xFA\xCE\xDE\xAD\xBE\xEF"
			"\xAB\xAD\xDA\xD2",
			20, true),

		CharString_createRefSizedConst(
			"\xD6\x09\xB1\xF0\x56\x63\x7A\x0D\x46\xDF\x99\x8D\x88\xE5\x22\x2A"
			"\xB2\xC2\x84\x65\x12\x15\x35\x24\xC0\x89\x5E\x81\x08\x00\x0F\x10"
			"\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C\x1D\x1E\x1F\x20"
			"\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C\x2D\x2E\x2F\x30"
			"\x31\x32\x33\x34\x00\x01",
			70, true),

		CharString_createRefSizedConst(
			"\xD6\x09\xB1\xF0\x56\x63\x7A\x0D\x46\xDF\x99\x8D\x88\xE5\x2E\x00"
			"\xB2\xC2\x84\x65\x12\x15\x35\x24\xC0\x89\x5E\x81",
			28, true),

		CharString_createRefSizedConst(
			"\xE2\x01\x06\xD7\xCD\x0D\xF0\x76\x1E\x8D\xCD\x3D\x88\xE5\x40\x00"
			"\x76\xD4\x57\xED\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18"
			"\x19\x1A\x1B\x1C\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28"
			"\x29\x2A\x2B\x2C\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38"
			"\x39\x3A\x00\x03",
			68, true),

		CharString_createRefSizedConst(
			"\xE2\x01\x06\xD7\xCD\x0D\xF0\x76\x1E\x8D\xCD\x3D\x88\xE5\x4C\x2A"
			"\x76\xD4\x57\xED",
			20, true),

		CharString_createRefSizedConst(
			"\x84\xC5\xD5\x13\xD2\xAA\xF6\xE5\xBB\xD2\x72\x77\x88\xE5\x23\x00"
			"\x89\x32\xD6\x12\x7C\xFD\xE9\xF9\xE3\x37\x24\xC6\x08\x00\x0F\x10"
			"\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C\x1D\x1E\x1F\x20"
			"\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C\x2D\x2E\x2F\x30"
			"\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3A\x3B\x3C\x3D\x3E\x3F\x00"
			"\x05",
			81, true),

		CharString_createRefSizedConst(
			"\x84\xC5\xD5\x13\xD2\xAA\xF6\xE5\xBB\xD2\x72\x77\x88\xE5\x2F\x00"
			"\x89\x32\xD6\x12\x7C\xFD\xE9\xF9\xE3\x37\x24\xC6",
			28, true),

		CharString_createRefSizedConst(
			"\x68\xF2\xE7\x76\x96\xCE\x7A\xE8\xE2\xCA\x4E\xC5\x88\xE5\x41\x00"
			"\x2E\x58\x49\x5C\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18"
			"\x19\x1A\x1B\x1C\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28"
			"\x29\x2A\x2B\x2C\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38"
			"\x39\x3A\x3B\x3C\x3D\x3E\x3F\x40\x41\x42\x43\x44\x45\x46\x47\x48"
			"\x49\x4A\x4B\x4C\x4D\x00\x07",
			87, true),

		CharString_createRefSizedConst(
			"\x68\xF2\xE7\x76\x96\xCE\x7A\xE8\xE2\xCA\x4E\xC5\x88\xE5\x4D\x00"
			"\x2E\x58\x49\x5C",
			20, true),
	};

	static const U8 ivs[][13] = {
		"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
		"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
		"\xCA\xFE\xBA\xBE\xFA\xCE\xDB\xAD\xDE\xCA\xF8\x88",
		"\xCA\xFE\xBA\xBE\xFA\xCE\xDB\xAD\xDE\xCA\xF8\x88",
		"\x12\x15\x35\x24\xC0\x89\x5E\x81\xB2\xC2\x84\x65",
		"\x12\x15\x35\x24\xC0\x89\x5E\x81\xB2\xC2\x84\x65",
		"\xF0\x76\x1E\x8D\xCD\x3D\x00\x01\x76\xD4\x57\xED",
		"\xF0\x76\x1E\x8D\xCD\x3D\x00\x01\x76\xD4\x57\xED",
		"\x7C\xFD\xE9\xF9\xE3\x37\x24\xC6\x89\x32\xD6\x12",
		"\x7C\xFD\xE9\xF9\xE3\x37\x24\xC6\x89\x32\xD6\x12",
		"\x7A\xE8\xE2\xCA\x4E\xC5\x00\x01\x2E\x58\x49\x5C",
		"\x7A\xE8\xE2\xCA\x4E\xC5\x00\x01\x2E\x58\x49\x5C"
	};

	const CharString results[] = {

		CharString_createRefSizedConst(
			"\x53\x0F\x8A\xFB\xC7\x45\x36\xB9\xA9\x63\xB4\xF1\xC4\xCB\x73\x8B",
			16, true),

		CharString_createRefSizedConst(
			"\xCE\xA7\x40\x3D\x4D\x60\x6B\x6E\x07\x4E\xC5\xD3\xBA\xF3\x9D\x18"
			"\xD0\xD1\xC8\xA7\x99\x99\x6B\xF0\x26\x5B\x98\xB5\xD4\x8A\xB9\x19",
			32, true),

		CharString_createRefSizedConst(
			"\x52\x2D\xC1\xF0\x99\x56\x7D\x07\xF4\x7F\x37\xA3\x2A\x84\x42\x7D"
			"\x64\x3A\x8C\xDC\xBF\xE5\xC0\xC9\x75\x98\xA2\xBD\x25\x55\xD1\xAA"
			"\x8C\xB0\x8E\x48\x59\x0D\xBB\x3D\xA7\xB0\x8B\x10\x56\x82\x88\x38"
			"\xC5\xF6\x1E\x63\x93\xBA\x7A\x0A\xBC\xC9\xF6\x62\x89\x80\x15\xAD"
			"\xB0\x94\xDA\xC5\xD9\x34\x71\xBD\xEC\x1A\x50\x22\x70\xE3\xCC\x6C",
			80, true),

		CharString_createRefSizedConst(
			"\x52\x2D\xC1\xF0\x99\x56\x7D\x07\xF4\x7F\x37\xA3\x2A\x84\x42\x7D"
			"\x64\x3A\x8C\xDC\xBF\xE5\xC0\xC9\x75\x98\xA2\xBD\x25\x55\xD1\xAA"
			"\x8C\xB0\x8E\x48\x59\x0D\xBB\x3D\xA7\xB0\x8B\x10\x56\x82\x88\x38"
			"\xC5\xF6\x1E\x63\x93\xBA\x7A\x0A\xBC\xC9\xF6\x62"
			"\x76\xFC\x6E\xCE\x0F\x4E\x17\x68\xCD\xDF\x88\x53\xBB\x2D\x55\x1B",
			76, true),

		CharString_createRefSizedConst(
			"\x2F\x0B\xC5\xAF\x40\x9E\x06\xD6\x09\xEA\x8B\x7D\x0F\xA5\xEA\x50",
			16, true),

		CharString_createRefSizedConst(
			"\xE2\x00\x6E\xB4\x2F\x52\x77\x02\x2D\x9B\x19\x92\x5B\xC4\x19\xD7"
			"\xA5\x92\x66\x6C\x92\x5F\xE2\xEF\x71\x8E\xB4\xE3\x08\xEF\xEA\xA7"
			"\xC5\x27\x3B\x39\x41\x18\x86\x0A\x5B\xE2\xA9\x7F\x56\xAB\x78\x36"
			"\x5C\xA5\x97\xCD\xBB\x3E\xDB\x8D\x1A\x11\x51\xEA\x0A\xF7\xB4\x36",
			64, true),

		CharString_createRefSizedConst(
			"\x35\x21\x7C\x77\x4B\xBC\x31\xB6\x31\x66\xBC\xF9\xD4\xAB\xED\x07",
			16, true),

		CharString_createRefSizedConst(
			"\xC1\x62\x3F\x55\x73\x0C\x93\x53\x30\x97\xAD\xDA\xD2\x56\x64\x96"
			"\x61\x25\x35\x2B\x43\xAD\xAC\xBD\x61\xC5\xEF\x3A\xC9\x0B\x5B\xEE"
			"\x92\x9C\xE4\x63\x0E\xA7\x9F\x6C\xE5\x19"
			"\x12\xAF\x39\xC2\xD1\xFD\xC2\x05\x1F\x8B\x7B\x3C\x9D\x39\x7E\xF2",
			58, true),

		CharString_createRefSizedConst(
			"\x6E\xE1\x60\xE8\xFA\xEC\xA4\xB3\x6C\x86\xB2\x34\x92\x0C\xA9\x75",
			16, true),

		CharString_createRefSizedConst(
			"\x11\x02\x22\xFF\x80\x50\xCB\xEC\xE6\x6A\x81\x3A\xD0\x9A\x73\xED"
			"\x7A\x9A\x08\x9C\x10\x6B\x95\x93\x89\x16\x8E\xD6\xE8\x69\x8E\xA9"
			"\x02\xEB\x12\x77\xDB\xEC\x2E\x68\xE4\x73\x15\x5A\x15\xA7\xDA\xEE"
			"\xD4"
			"\xA1\x0F\x4E\x05\x13\x9C\x23\xDF\x00\xB3\xAA\xDC\x71\xF0\x59\x6A",
			65, true),

		CharString_createRefSizedConst(
			"\x00\xBD\xA1\xB7\xE8\x76\x08\xBC\xBF\x47\x0F\x12\x15\x7F\x4C\x07",
			16, true),

		CharString_createRefSizedConst(
			"\xBA\x8A\xE3\x1B\xC5\x06\x48\x6D\x68\x73\xE4\xFC\xE4\x60\xE7\xDC"
			"\x57\x59\x1F\xF0\x06\x11\xF3\x1C\x38\x34\xFE\x1C\x04\xAD\x80\xB6"
			"\x68\x03\xAF\xCF\x5B\x27\xE6\x33\x3F\xA6\x7C\x99\xDA\x47\xC2\xF0"
			"\xCE\xD6\x8D\x53\x1B\xD7\x41\xA9\x43\xCF\xF7\xA6\x71\x3B\xD0"
			"\x26\x11\xCD\x7D\xAA\x01\xD6\x1C\x5C\x88\x6D\xC1\xA8\x17\x01\x07",
			79, true),
	};

	runAesVectors(t, EBufferEncryptionType_AES256GCM, sizeof(keys) / sizeof(keys[0]), keys, plainTexts, aad, ivs, results);

	//Test different chunkSizes for AVX2/AVX512/etc.

	Test_aesValidation(t);
}

void Test_aes128gcm(Test *t) {

	Test_setModule(t, "aes128gcm");

	const CharString keys[] = {
		CharString_createRefSizedConst("\xAD\x7A\x2B\xD0\x3E\xAC\x83\x5A\x6F\x62\x0F\xDC\xB5\x06\xB3\x45", 16, true),
		CharString_createRefSizedConst("\xAD\x7A\x2B\xD0\x3E\xAC\x83\x5A\x6F\x62\x0F\xDC\xB5\x06\xB3\x45", 16, true),
		CharString_createRefSizedConst("\x07\x1B\x11\x3B\x0C\xA7\x43\xFE\xCC\xCF\x3D\x05\x1F\x73\x73\x82", 16, true),
		CharString_createRefSizedConst("\x07\x1B\x11\x3B\x0C\xA7\x43\xFE\xCC\xCF\x3D\x05\x1F\x73\x73\x82", 16, true),
		CharString_createRefSizedConst("\x01\x3F\xE0\x0B\x5F\x11\xBE\x7F\x86\x6D\x0C\xBB\xC5\x5A\x7A\x90", 16, true),
		CharString_createRefSizedConst("\x01\x3F\xE0\x0B\x5F\x11\xBE\x7F\x86\x6D\x0C\xBB\xC5\x5A\x7A\x90", 16, true),
		CharString_createRefSizedConst("\x88\xEE\x08\x7F\xD9\x5D\xA9\xFB\xF6\x72\x5A\xA9\xD7\x57\xB0\xCD", 16, true),
		CharString_createRefSizedConst("\x88\xEE\x08\x7F\xD9\x5D\xA9\xFB\xF6\x72\x5A\xA9\xD7\x57\xB0\xCD", 16, true),
		CharString_createRefSizedConst("\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 16, true),
		CharString_createRefSizedConst("\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 16, true),
		CharString_createRefSizedConst("\xFE\xFF\xE9\x92\x86\x65\x73\x1C\x6D\x6A\x8F\x94\x67\x30\x83\x08", 16, true),
		CharString_createRefSizedConst("\xFE\xFF\xE9\x92\x86\x65\x73\x1C\x6D\x6A\x8F\x94\x67\x30\x83\x08", 16, true),
	};

	const CharString plainTexts[] = {

		CharString_createNull(),

		CharString_createRefSizedConst(
			"\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C"
			"\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C"
			"\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3A\x00\x02",
			48, true),

		CharString_createNull(),

		CharString_createRefSizedConst(
			"\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C"
			"\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C"
			"\x2D\x2E\x2F\x30\x31\x32\x33\x34\x00\x04",
			42, true),

		CharString_createNull(),

		CharString_createRefSizedConst(
			"\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C"
			"\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C"
			"\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3A\x3B\x00"
			"\x06",
			49, true),

		CharString_createNull(),

		CharString_createRefSizedConst(
			"\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C"
			"\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C"
			"\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3A\x3B\x3C"
			"\x3D\x3E\x3F\x40\x41\x42\x43\x44\x45\x46\x47\x48\x49\x00\x08",
			63, true),

		CharString_createNull(),

		CharString_createRefSizedConst(
			"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
			16, true),

		CharString_createRefSizedConst(
			"\xD9\x31\x32\x25\xF8\x84\x06\xE5\xA5\x59\x09\xC5\xAF\xF5\x26\x9A"
			"\x86\xA7\xA9\x53\x15\x34\xF7\xDA\x2E\x4C\x30\x3D\x8A\x31\x8A\x72"
			"\x1C\x3C\x0C\x95\x95\x68\x09\x53\x2F\xCF\x0E\x24\x49\xA6\xB5\x25"
			"\xB1\x6A\xED\xF5\xAA\x0D\xE6\x57\xBA\x63\x7B\x39\x1A\xAF\xD2\x55",
			64, true),

		CharString_createRefSizedConst(
			"\xD9\x31\x32\x25\xF8\x84\x06\xE5\xA5\x59\x09\xC5\xAF\xF5\x26\x9A"
			"\x86\xA7\xA9\x53\x15\x34\xF7\xDA\x2E\x4C\x30\x3D\x8A\x31\x8A\x72"
			"\x1C\x3C\x0C\x95\x95\x68\x09\x53\x2F\xCF\x0E\x24\x49\xA6\xB5\x25"
			"\xB1\x6A\xED\xF5\xAA\x0D\xE6\x57\xBA\x63\x7B\x39",
			60, true),
	};

	const CharString aad[] = {

		CharString_createRefSizedConst(
			"\xD6\x09\xB1\xF0\x56\x63\x7A\x0D\x46\xDF\x99\x8D\x88\xE5\x22\x2A"
			"\xB2\xC2\x84\x65\x12\x15\x35\x24\xC0\x89\x5E\x81\x08\x00\x0F\x10"
			"\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C\x1D\x1E\x1F\x20"
			"\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C\x2D\x2E\x2F\x30"
			"\x31\x32\x33\x34\x00\x01",
			70, true),

		CharString_createRefSizedConst(
			"\xD6\x09\xB1\xF0\x56\x63\x7A\x0D\x46\xDF\x99\x8D\x88\xE5\x2E\x00"
			"\xB2\xC2\x84\x65\x12\x15\x35\x24\xC0\x89\x5E\x81",
			28, true),

		CharString_createRefSizedConst(
			"\xE2\x01\x06\xD7\xCD\x0D\xF0\x76\x1E\x8D\xCD\x3D\x88\xE5\x40\x00"
			"\x76\xD4\x57\xED\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18"
			"\x19\x1A\x1B\x1C\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28"
			"\x29\x2A\x2B\x2C\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38"
			"\x39\x3A\x00\x03",
			68, true),

		CharString_createRefSizedConst(
			"\xE2\x01\x06\xD7\xCD\x0D\xF0\x76\x1E\x8D\xCD\x3D\x88\xE5\x4C\x2A"
			"\x76\xD4\x57\xED",
			20, true),

		CharString_createRefSizedConst(
			"\x84\xC5\xD5\x13\xD2\xAA\xF6\xE5\xBB\xD2\x72\x77\x88\xE5\x23\x00"
			"\x89\x32\xD6\x12\x7C\xFD\xE9\xF9\xE3\x37\x24\xC6\x08\x00\x0F\x10"
			"\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1A\x1B\x1C\x1D\x1E\x1F\x20"
			"\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C\x2D\x2E\x2F\x30"
			"\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3A\x3B\x3C\x3D\x3E\x3F\x00"
			"\x05",
			81, true),

		CharString_createRefSizedConst(
			"\x84\xC5\xD5\x13\xD2\xAA\xF6\xE5\xBB\xD2\x72\x77\x88\xE5\x2F\x00"
			"\x89\x32\xD6\x12\x7C\xFD\xE9\xF9\xE3\x37\x24\xC6",
			28, true),

		CharString_createRefSizedConst(
			"\x68\xF2\xE7\x76\x96\xCE\x7A\xE8\xE2\xCA\x4E\xC5\x88\xE5\x41\x00"
			"\x2E\x58\x49\x5C\x08\x00\x0F\x10\x11\x12\x13\x14\x15\x16\x17\x18"
			"\x19\x1A\x1B\x1C\x1D\x1E\x1F\x20\x21\x22\x23\x24\x25\x26\x27\x28"
			"\x29\x2A\x2B\x2C\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38"
			"\x39\x3A\x3B\x3C\x3D\x3E\x3F\x40\x41\x42\x43\x44\x45\x46\x47\x48"
			"\x49\x4A\x4B\x4C\x4D\x00\x07",
			87, true),

		CharString_createRefSizedConst(
			"\x68\xF2\xE7\x76\x96\xCE\x7A\xE8\xE2\xCA\x4E\xC5\x88\xE5\x4D\x00"
			"\x2E\x58\x49\x5C",
			20, true),

		CharString_createNull(),
		CharString_createNull(),
		CharString_createNull(),

		CharString_createRefSizedConst(
			"\xFE\xED\xFA\xCE\xDE\xAD\xBE\xEF\xFE\xED\xFA\xCE\xDE\xAD\xBE\xEF"
			"\xAB\xAD\xDA\xD2",
			20, true),
	};

	const U8 ivs[][13] = {
		"\x12\x15\x35\x24\xC0\x89\x5E\x81\xB2\xC2\x84\x65",
		"\x12\x15\x35\x24\xC0\x89\x5E\x81\xB2\xC2\x84\x65",
		"\xF0\x76\x1E\x8D\xCD\x3D\x00\x01\x76\xD4\x57\xED",
		"\xF0\x76\x1E\x8D\xCD\x3D\x00\x01\x76\xD4\x57\xED",
		"\x7C\xFD\xE9\xF9\xE3\x37\x24\xC6\x89\x32\xD6\x12",
		"\x7C\xFD\xE9\xF9\xE3\x37\x24\xC6\x89\x32\xD6\x12",
		"\x7A\xE8\xE2\xCA\x4E\xC5\x00\x01\x2E\x58\x49\x5C",
		"\x7A\xE8\xE2\xCA\x4E\xC5\x00\x01\x2E\x58\x49\x5C",
		{ 0 },
		{ 0 },
		"\xCA\xFE\xBA\xBE\xFA\xCE\xDB\xAD\xDE\xCA\xF8\x88",
		"\xCA\xFE\xBA\xBE\xFA\xCE\xDB\xAD\xDE\xCA\xF8\x88",
	};

	const CharString results[] = {

		CharString_createRefSizedConst("\xF0\x94\x78\xA9\xB0\x90\x07\xD0\x6F\x46\xE9\xB6\xA1\xDA\x25\xDD", 16, true),

		CharString_createRefSizedConst(
			"\x70\x1A\xFA\x1C\xC0\x39\xC0\xD7\x65\x12\x8A\x66\x5D\xAB\x69\x24"
			"\x38\x99\xBF\x73\x18\xCC\xDC\x81\xC9\x93\x1D\xA1\x7F\xBE\x8E\xDD"
			"\x7D\x17\xCB\x8B\x4C\x26\xFC\x81\xE3\x28\x4F\x2B\x7F\xBA\x71\x3D"
			"\x4F\x8D\x55\xE7\xD3\xF0\x6F\xD5\xA1\x3C\x0C\x29\xB9\xD5\xB8\x80",
			64, true),

		CharString_createRefSizedConst("\x0C\x01\x7B\xC7\x3B\x22\x7D\xFC\xC9\xBA\xFA\x1C\x41\xAC\xC3\x53", 16, true),

		CharString_createRefSizedConst(
			"\x13\xB4\xC7\x2B\x38\x9D\xC5\x01\x8E\x72\xA1\x71\xDD\x85\xA5\xD3"
			"\x75\x22\x74\xD3\xA0\x19\xFB\xCA\xED\x09\xA4\x25\xCD\x9B\x2E\x1C"
			"\x9B\x72\xEE\xE7\xC9\xDE\x7D\x52\xB3\xF3"
			"\xD6\xA5\x28\x4F\x4A\x6D\x3F\xE2\x2A\x5D\x6C\x2B\x96\x04\x94\xC3",
			58, true),

		CharString_createRefSizedConst("\x21\x78\x67\xE5\x0C\x2D\xAD\x74\xC2\x8C\x3B\x50\xAB\xDF\x69\x5A", 16, true),

		CharString_createRefSizedConst(
			"\x3A\x4D\xE6\xFA\x32\x19\x10\x14\xDB\xB3\x03\xD9\x2E\xE3\xA9\xE8"
			"\xA1\xB5\x99\xC1\x4D\x22\xFB\x08\x00\x96\xE1\x38\x11\x81\x6A\x3C"
			"\x9C\x9B\xCF\x7C\x1B\x9B\x96\xDA\x80\x92\x04\xE2\x9D\x0E\x2A\x76"
			"\x42"
			"\xBF\xD3\x10\xA4\x83\x7C\x81\x6C\xCF\xA5\xAC\x23\xAB\x00\x39\x88",
			65, true),

		CharString_createRefSizedConst("\x07\x92\x2B\x8E\xBC\xF1\x0B\xB2\x29\x75\x88\xCA\x4C\x61\x45\x23", 16, true),

		CharString_createRefSizedConst(
			"\xC3\x1F\x53\xD9\x9E\x56\x87\xF7\x36\x51\x19\xB8\x32\xD2\xAA\xE7"
			"\x07\x41\xD5\x93\xF1\xF9\xE2\xAB\x34\x55\x77\x9B\x07\x8E\xB8\xFE"
			"\xAC\xDF\xEC\x1F\x8E\x3E\x52\x77\xF8\x18\x0B\x43\x36\x1F\x65\x12"
			"\xAD\xB1\x6D\x2E\x38\x54\x8A\x2C\x71\x9D\xBA\x72\x28\xD8\x40"
			"\x88\xF8\x75\x7A\xDB\x8A\xA7\x88\xD8\xF6\x5A\xD6\x68\xBE\x70\xE7",
			79, true),

		CharString_createRefSizedConst("\x58\xE2\xFC\xCE\xFA\x7E\x30\x61\x36\x7F\x1D\x57\xA4\xE7\x45\x5A", 16, true),

		CharString_createRefSizedConst(
			"\x03\x88\xDA\xCE\x60\xB6\xA3\x92\xF3\x28\xC2\xB9\x71\xB2\xFE\x78"
			"\xAB\x6E\x47\xD4\x2C\xEC\x13\xBD\xF5\x3A\x67\xB2\x12\x57\xBD\xDF",
			32, true),

		CharString_createRefSizedConst(
			"\x42\x83\x1E\xC2\x21\x77\x74\x24\x4B\x72\x21\xB7\x84\xD0\xD4\x9C"
			"\xE3\xAA\x21\x2F\x2C\x02\xA4\xE0\x35\xC1\x7E\x23\x29\xAC\xA1\x2E"
			"\x21\xD5\x14\xB2\x54\x66\x93\x1C\x7D\x8F\x6A\x5A\xAC\x84\xAA\x05"
			"\x1B\xA3\x0B\x39\x6A\x0A\xAC\x97\x3D\x58\xE0\x91\x47\x3F\x59\x85"
			"\x4D\x5C\x2A\xF3\x27\xCD\x64\xA6\x2C\xF3\x5A\xBD\x2B\xA6\xFA\xB4",
			80, true),

		CharString_createRefSizedConst(
			"\x42\x83\x1E\xC2\x21\x77\x74\x24\x4B\x72\x21\xB7\x84\xD0\xD4\x9C"
			"\xE3\xAA\x21\x2F\x2C\x02\xA4\xE0\x35\xC1\x7E\x23\x29\xAC\xA1\x2E"
			"\x21\xD5\x14\xB2\x54\x66\x93\x1C\x7D\x8F\x6A\x5A\xAC\x84\xAA\x05"
			"\x1B\xA3\x0B\x39\x6A\x0A\xAC\x97\x3D\x58\xE0\x91"
			"\x5B\xC9\x4F\xBC\x32\x21\xA5\xDB\x94\xFA\xE9\x5A\xE7\x12\x1A\x47",
			76, true),
	};

	runAesVectors(t, EBufferEncryptionType_AES128GCM, sizeof(keys) / sizeof(keys[0]), keys, plainTexts, aad, ivs, results);
}
