/* OxC3(Oxsomi core 3), a general framework and toolset for cross-platform applications.
*  Copyright (C) 2023 - 2026 Oxsomi / Nielsbishere (Niels Brunekreef)
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program. If not, see https://github.com/Oxsomi/core3/blob/main/LICENSE.
*  Be aware that GPL3 requires closed source products to be GPL3 too if released to the public.
*  To prevent this a separate license will have to be requested at contact@osomi.net for a premium;
*  This is called dual licensing.
*/

//types/base/c8.hpp
//
//GENERATED by src/tools/generate_hpp.py from include/types/base/c8.h - do not edit by hand.
//Re-run the generator (or `--check` in CI) after changing the C header.

#pragma once
#include <stdbool.h>
#include <stdint.h>
#include <assert.h>

namespace oxc {

	namespace c {
		#include "types/base/c8.h"
	}

	//Generated wrapper around the C C8.
	//Character classification and conversion; C8 is a typedef for a char, not a struct.
	namespace C8 {

		[[nodiscard]] inline c::C8 toLower(c::C8 c) noexcept {
			return c::C8_toLower(c);
		}

		[[nodiscard]] inline c::C8 toUpper(c::C8 c) noexcept {
			return c::C8_toUpper(c);
		}

		[[nodiscard]] inline c::C8 transform(c::C8 c, c::EStringTransform transform) noexcept {
			return c::C8_transform(c, transform);
		}

		[[nodiscard]] inline c::Bool isBin(c::C8 c) noexcept {
			return c::C8_isBin(c);
		}

		[[nodiscard]] inline c::Bool isOct(c::C8 c) noexcept {
			return c::C8_isOct(c);
		}

		[[nodiscard]] inline c::Bool isDec(c::C8 c) noexcept {
			return c::C8_isDec(c);
		}

		[[nodiscard]] inline c::Bool isUpperCase(c::C8 c) noexcept {
			return c::C8_isUpperCase(c);
		}

		[[nodiscard]] inline c::Bool isLowerCase(c::C8 c) noexcept {
			return c::C8_isLowerCase(c);
		}

		[[nodiscard]] inline c::Bool isUpperCaseHex(c::C8 c) noexcept {
			return c::C8_isUpperCaseHex(c);
		}

		[[nodiscard]] inline c::Bool isLowerCaseHex(c::C8 c) noexcept {
			return c::C8_isLowerCaseHex(c);
		}

		[[nodiscard]] inline c::Bool isWhitespace(c::C8 c) noexcept {
			return c::C8_isWhitespace(c);
		}

		[[nodiscard]] inline c::Bool isNewLine(c::C8 c) noexcept {
			return c::C8_isNewLine(c);
		}

		[[nodiscard]] inline c::Bool isHex(c::C8 c) noexcept {
			return c::C8_isHex(c);
		}

		[[nodiscard]] inline c::Bool isNyto(c::C8 c) noexcept {
			return c::C8_isNyto(c);
		}

		[[nodiscard]] inline c::Bool isAlphaNumeric(c::C8 c) noexcept {
			return c::C8_isAlphaNumeric(c);
		}

		[[nodiscard]] inline c::Bool isAlpha(c::C8 c) noexcept {
			return c::C8_isAlpha(c);
		}

		[[nodiscard]] inline c::Bool isSymbol(c::C8 c) noexcept {
			return c::C8_isSymbol(c);
		}

		[[nodiscard]] inline c::Bool isValidAscii(c::C8 c) noexcept {
			return c::C8_isValidAscii(c);
		}

		[[nodiscard]] inline c::Bool isValidFileName(c::C8 c) noexcept {
			return c::C8_isValidFileName(c);
		}

		[[nodiscard]] inline c::U8 bin(c::C8 c) noexcept {
			return c::C8_bin(c);
		}

		[[nodiscard]] inline c::U8 oct(c::C8 c) noexcept {
			return c::C8_oct(c);
		}

		[[nodiscard]] inline c::U8 dec(c::C8 c) noexcept {
			return c::C8_dec(c);
		}

		[[nodiscard]] inline c::U8 hex(c::C8 c) noexcept {
			return c::C8_hex(c);
		}

		[[nodiscard]] inline c::U8 nyto(c::C8 c) noexcept {
			return c::C8_nyto(c);
		}

		[[nodiscard]] inline c::C8 createBin(c::U8 v) noexcept {
			return c::C8_createBin(v);
		}

		[[nodiscard]] inline c::C8 createOct(c::U8 v) noexcept {
			return c::C8_createOct(v);
		}

		[[nodiscard]] inline c::C8 createDec(c::U8 v) noexcept {
			return c::C8_createDec(v);
		}

		[[nodiscard]] inline c::C8 createHex(c::U8 v) noexcept {
			return c::C8_createHex(v);
		}

		[[nodiscard]] inline c::C8 createNyto(c::U8 v) noexcept {
			return c::C8_createNyto(v);
		}

	}
}
