/* OxC3(Oxsomi core 3), a general framework and toolset for cross-platform applications.
*  Copyright (C) 2023 - 2026 Oxsomi / Nielsbishere (Niels Brunekreef)
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program. If not, see https://github.com/Oxsomi/core3/blob/main/LICENSE.
*  Be aware that GPL3 requires closed source products to be GPL3 too if released to the public.
*  To prevent this a separate license will have to be requested at contact@osomi.net for a premium;
*  This is called dual licensing.
*/

//types/base/error.hpp
//
//GENERATED by src/tools/generate_hpp.py from include/types/base/error.h - do not edit by hand.
//Re-run the generator (or `--check` in CI) after changing the C header.

#pragma once
#include <stdbool.h>
#include <stdint.h>
#include <assert.h>

namespace oxc {

	namespace c {
		#include "types/base/error.h"
	}

	//Generated wrapper around the C Error.
	//Factories for the C Error struct.
	//A namespace rather than a class: Error is a plain value that the C API fills in by pointer,
	// so there's nothing to own and no invariant to protect.
	//Construct one here and pass handle() to C, or take one back from a C call and inspect it.
	namespace Error {

		inline void captureStackTrace(void **stackTrace, c::U8 stackSize, c::U8 skip) noexcept {
			c::Error_captureStackTrace(stackTrace, stackSize, skip);
		}

		inline void fillStackTrace(c::Error *e_rr = nullptr) noexcept {
			c::Error_fillStackTrace(e_rr);
		}

		[[nodiscard]] inline c::Error platformError(c::U32 subId, c::U64 platformError, const c::C8 *errorStr) noexcept {
			return c::Error_platformError(subId, platformError, errorStr);
		}

		[[nodiscard]] inline c::Error outOfMemory(c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_outOfMemory(subId, errorStr);
		}

		[[nodiscard]] inline c::Error outOfBounds(c::U32 paramId, c::U64 id, c::U64 limit, const c::C8 *errorStr) noexcept {
			return c::Error_outOfBounds(paramId, id, limit, errorStr);
		}

		[[nodiscard]] inline c::Error nullPointer(c::U32 paramId, const c::C8 *errorStr) noexcept {
			return c::Error_nullPointer(paramId, errorStr);
		}

		[[nodiscard]] inline c::Error unauthorized(c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_unauthorized(subId, errorStr);
		}

		[[nodiscard]] inline c::Error notFound(c::U32 subId, c::U32 paramId, const c::C8 *errorStr) noexcept {
			return c::Error_notFound(subId, paramId, errorStr);
		}

		[[nodiscard]] inline c::Error divideByZero(c::U32 subId, c::U64 a, c::U64 b, const c::C8 *errorStr) noexcept {
			return c::Error_divideByZero(subId, a, b, errorStr);
		}

		[[nodiscard]] inline c::Error overflow(c::U32 paramId, c::U64 a, c::U64 b, const c::C8 *errorStr) noexcept {
			return c::Error_overflow(paramId, a, b, errorStr);
		}

		[[nodiscard]] inline c::Error underflow(c::U32 paramId, c::U64 a, c::U64 b, const c::C8 *errorStr) noexcept {
			return c::Error_underflow(paramId, a, b, errorStr);
		}

		[[nodiscard]] inline c::Error naN(c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_NaN(subId, errorStr);
		}

		[[nodiscard]] inline c::Error invalidEnum(c::U32 paramId, c::U64 value, c::U64 maxValue, const c::C8 *errorStr) noexcept {
			return c::Error_invalidEnum(paramId, value, maxValue, errorStr);
		}

		[[nodiscard]] inline c::Error invalidParameter(c::U32 paramId, c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_invalidParameter(paramId, subId, errorStr);
		}

		[[nodiscard]] inline c::Error invalidOperation(c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_invalidOperation(subId, errorStr);
		}

		[[nodiscard]] inline c::Error invalidCast(c::U32 subId, c::U32 typeId, c::U32 castTypeId, const c::C8 *errorStr) noexcept {
			return c::Error_invalidCast(subId, typeId, castTypeId, errorStr);
		}

		[[nodiscard]] inline c::Error invalidState(c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_invalidState(subId, errorStr);
		}

		[[nodiscard]] inline c::Error rateLimit(c::U32 subId, c::U64 limit, const c::C8 *errorStr) noexcept {
			return c::Error_rateLimit(subId, limit, errorStr);
		}

		[[nodiscard]] inline c::Error loopLimit(c::U32 subId, c::U64 limit, const c::C8 *errorStr) noexcept {
			return c::Error_loopLimit(subId, limit, errorStr);
		}

		[[nodiscard]] inline c::Error alreadyDefined(c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_alreadyDefined(subId, errorStr);
		}

		[[nodiscard]] inline c::Error unimplemented(c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_unimplemented(subId, errorStr);
		}

		[[nodiscard]] inline c::Error unsupportedOperation(c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_unsupportedOperation(subId, errorStr);
		}

		[[nodiscard]] inline c::Error timedOut(c::U32 subId, c::U64 limit, const c::C8 *errorStr) noexcept {
			return c::Error_timedOut(subId, limit, errorStr);
		}

		[[nodiscard]] inline c::Error constData(c::U32 paramId, c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_constData(paramId, subId, errorStr);
		}

		[[nodiscard]] inline c::Error stderr(c::U32 subId, const c::C8 *errorStr) noexcept {
			return c::Error_stderr(subId, errorStr);
		}

		[[nodiscard]] inline c::Error none() noexcept {
			return c::Error_none();
		}

	}
}
