/* OxC3(Oxsomi core 3), a general framework and toolset for cross-platform applications.
*  Copyright (C) 2023 - 2026 Oxsomi / Nielsbishere (Niels Brunekreef)
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program. If not, see https://github.com/Oxsomi/core3/blob/main/LICENSE.
*  Be aware that GPL3 requires closed source products to be GPL3 too if released to the public.
*  To prevent this a separate license will have to be requested at contact@osomi.net for a premium;
*  This is called dual licensing.
*/

//types/base/time.hpp
//
//GENERATED by src/tools/generate_hpp.py from include/types/base/time.h - do not edit by hand.
//Re-run the generator (or `--check` in CI) after changing the C header.

#pragma once
#include <stdbool.h>
#include <stdint.h>
#include <assert.h>

namespace oxc {

	namespace c {
		#include "types/base/time.h"
		#include "types/base/string_base.h"
	}

	//Generated wrapper around the C Time.
	//Time has no instance state in C - every function is a free function over Ns - so this is a
	//namespace, not a class.
	namespace Time {

		[[nodiscard]] inline c::Ns now() noexcept {
			return c::Time_now();
		}

		[[nodiscard]] inline c::U64 clocks() noexcept {
			return c::Time_clocks();
		}

		[[nodiscard]] inline c::Ns date(const c::Date *date, c::Bool isLocalTime) noexcept {
			return c::Time_date(date, isLocalTime);
		}

		[[nodiscard]] inline c::Bool getDate(c::Ns timestamp, c::Date *date, c::Bool isLocalTime) noexcept {
			return c::Time_getDate(timestamp, date, isLocalTime);
		}

		[[nodiscard]] inline c::DNs dns(c::Ns timeStamp0, c::Ns timeStamp1) noexcept {
			return c::Time_dns(timeStamp0, timeStamp1);
		}

		[[nodiscard]] inline c::F64 dt(c::Ns timeStamp0, c::Ns timeStamp1) noexcept {
			return c::Time_dt(timeStamp0, timeStamp1);
		}

		[[nodiscard]] inline c::I64 clocksElapsed(c::U64 prevClocks) noexcept {
			return c::Time_clocksElapsed(prevClocks);
		}

		[[nodiscard]] inline c::DNs elapsed(c::Ns prev) noexcept {
			return c::Time_elapsed(prev);
		}

		inline void format(c::Ns time, c::TimeFormat timeString, c::Bool isLocalTime) noexcept {
			c::Time_format(time, timeString, isLocalTime);
		}

		[[nodiscard]] inline c::Bool parseFormat(c::Ns *time, c::TimeFormat format, c::Bool isLocalTime) noexcept {
			return c::Time_parseFormat(time, format, isLocalTime);
		}

	}
}
