/* OxC3(Oxsomi core 3), a general framework and toolset for cross-platform applications.
*  Copyright (C) 2023 - 2026 Oxsomi / Nielsbishere (Niels Brunekreef)
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program. If not, see https://github.com/Oxsomi/core3/blob/main/LICENSE.
*  Be aware that GPL3 requires closed source products to be GPL3 too if released to the public.
*  To prevent this a separate license will have to be requested at contact@osomi.net for a premium;
*  This is called dual licensing.
*/

//types/container/buffer.hpp
//
//GENERATED by src/tools/generate_hpp.py from include/types/container/buffer.h - do not edit by hand.
//Re-run the generator (or `--check` in CI) after changing the C header.

#pragma once
#include <stdbool.h>
#include <stdint.h>
#include <assert.h>

namespace oxc {

	namespace c {
		#include "types/container/buffer.h"
		#include "types/base/error.h"
		#include "types/base/allocator.h"
	}

	//Generated wrapper around the C Buffer.
	//RAII around the C Buffer. Only the allocating half is owned; the createRef* helpers in
	//buffer_base.h deliberately aren't wrapped, since a ref must not be freed and that distinction
	//is exactly what this type is for. Use handle() to build one and hand it to C.
	class Buffer {

		c::Buffer self;
		const c::Allocator *alloc;

	public:

		Buffer(const c::Allocator &alloc) noexcept : self{}, alloc(&alloc) {}
		~Buffer() noexcept { release(); }

		Buffer(const Buffer&) = delete;
		Buffer &operator=(const Buffer&) = delete;

		Buffer(Buffer &&other) noexcept : self(other.self), alloc(other.alloc) {
			other.self = c::Buffer{};
		}

		Buffer &operator=(Buffer &&other) noexcept {

			if(this == &other)
				return *this;

			release();
			self = other.self;
			alloc = other.alloc;
			other.self = c::Buffer{};
			return *this;
		}

		void release() noexcept {
			c::Buffer_free(&self, alloc);
			self = c::Buffer{};
		}

		[[nodiscard]] c::Bool createZeroBits(c::U64 length, c::Error *e_rr = nullptr) noexcept {
			release();
			return c::Buffer_createZeroBits(length, alloc, &self, e_rr);
		}

		[[nodiscard]] c::Bool createOneBits(c::U64 length, c::Error *e_rr = nullptr) noexcept {
			release();
			return c::Buffer_createOneBits(length, alloc, &self, e_rr);
		}

		[[nodiscard]] c::Bool createBits(c::U64 length, c::Bool value, c::Error *e_rr = nullptr) noexcept {
			release();
			return c::Buffer_createBits(length, value, alloc, &self, e_rr);
		}

		[[nodiscard]] c::Bool createEmptyBytes(c::U64 length, c::Error *e_rr = nullptr) noexcept {
			release();
			return c::Buffer_createEmptyBytes(length, alloc, &self, e_rr);
		}

		[[nodiscard]] c::Bool createUninitializedBytes(c::U64 length, c::Error *e_rr = nullptr) noexcept {
			release();
			return c::Buffer_createUninitializedBytes(length, alloc, &self, e_rr);
		}

		[[nodiscard]] c::Bool resize(
			c::U64 newLen, c::Bool preserveContents, c::Bool clearUnsetContents, c::Error *e_rr = nullptr
		) noexcept {
			return c::Buffer_resize(&self, newLen, preserveContents, clearUnsetContents, alloc, e_rr);
		}

		[[nodiscard]] c::Bool combine(const c::Buffer *b, c::Buffer *output, c::Error *e_rr = nullptr) const noexcept {
			return c::Buffer_combine(&self, b, alloc, output, e_rr);
		}

		[[nodiscard]] c::Bool readAsUTF8(c::U64 i, c::UnicodeCodePointInfo *codepoint, c::Error *e_rr = nullptr) const noexcept {
			return c::Buffer_readAsUTF8(self, i, codepoint, e_rr);
		}

		[[nodiscard]] c::Bool writeAsUTF8(
			c::U64 i, c::UnicodeCodePoint codepoint, c::U8 *bytes, c::Error *e_rr = nullptr
		) const noexcept {
			return c::Buffer_writeAsUTF8(self, i, codepoint, bytes, e_rr);
		}

		[[nodiscard]] c::Bool readAsUTF16(c::U64 i, c::UnicodeCodePointInfo *codepoint, c::Error *e_rr = nullptr) const noexcept {
			return c::Buffer_readAsUTF16(self, i, codepoint, e_rr);
		}

		[[nodiscard]] c::Bool writeAsUTF16(
			c::U64 i, c::UnicodeCodePoint codepoint, c::U8 *bytes, c::Error *e_rr = nullptr
		) const noexcept {
			return c::Buffer_writeAsUTF16(self, i, codepoint, bytes, e_rr);
		}

		[[nodiscard]] c::Bool isUnicode(c::F32 threshold, c::Bool isUTF16) const noexcept {
			return c::Buffer_isUnicode(self, threshold, isUTF16);
		}

		[[nodiscard]] c::Bool isUTF8(c::F32 threshold) const noexcept {
			return c::Buffer_isUTF8(self, threshold);
		}

		[[nodiscard]] c::Bool isUTF16(c::F32 threshold) const noexcept {
			return c::Buffer_isUTF16(self, threshold);
		}

		[[nodiscard]] c::U32 crc32cChained(c::U32 crcPrev) const noexcept {
			return c::Buffer_crc32cChained(self, crcPrev);
		}

		[[nodiscard]] c::U32 crc32cFallbackChained(c::U32 crcPrev) const noexcept {
			return c::Buffer_crc32cFallbackChained(self, crcPrev);
		}

		[[nodiscard]] c::U32 crc32cFallback() const noexcept {
			return c::Buffer_crc32cFallback(self);
		}

		[[nodiscard]] c::U32 crc32c() const noexcept {
			return c::Buffer_crc32c(self);
		}

		[[nodiscard]] static c::U64 fnv1a64Single(c::U64 a, c::U64 hash) noexcept {
			return c::Buffer_fnv1a64Single(a, hash);
		}

		[[nodiscard]] c::U64 fnv1a64(c::U64 hash) const noexcept {
			return c::Buffer_fnv1a64(self, hash);
		}

		[[nodiscard]] c::MD5Hash md5() const noexcept {
			return c::Buffer_md5(self);
		}

		void sha256(c::U32 output[8]) const noexcept {
			c::Buffer_sha256(self, output);
		}

		void sha256Fallback(c::U32 *output) const noexcept {
			c::Buffer_sha256Fallback(self, output);
		}

		[[nodiscard]] c::Bool csprng() const noexcept {
			return c::Buffer_csprng(self);
		}

		//Interop with C

		[[nodiscard]] c::Buffer &handle() noexcept { return self; }
		[[nodiscard]] const c::Buffer &handle() const noexcept { return self; }

		//Caller takes ownership; must free with the same allocator
		[[nodiscard]] c::Buffer steal() noexcept {
			c::Buffer tmp = self;
			self = c::Buffer{};
			return tmp;
		}
	};
}
