/* OxC3(Oxsomi core 3), a general framework and toolset for cross-platform applications.
*  Copyright (C) 2023 - 2026 Oxsomi / Nielsbishere (Niels Brunekreef)
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program. If not, see https://github.com/Oxsomi/core3/blob/main/LICENSE.
*  Be aware that GPL3 requires closed source products to be GPL3 too if released to the public.
*  To prevent this a separate license will have to be requested at contact@osomi.net for a premium;
*  This is called dual licensing.
*/

//types/container/list.hpp

#pragma once
#include <utility>
#include <type_traits>

//Pre-include system headers used by the C headers below at global scope;
//they must not be pulled in for the first time inside a namespace.

#include <stdbool.h>
#include <stdint.h>
#include <assert.h>

//RAII wrapper around the C TList system.
//This is pure syntax sugar: element storage, growth and freeing are all done by the
// existing C functions (ListX_pushBack, ListX_resize, ListX_free, ...), so anything built
// with it stays interoperable and ABI compatible with C code that consumes the raw list.
//
//Because TList generates a distinct C type + function set per element type, the wrapper
// is bound to those functions through a traits specialization generated by OXC_BIND_LIST,
// used at global scope after the C list was declared inside namespace oxc::c
// (the basic lists from list_basic_types.h are declared there by this header already):
//
//  OXC_BIND_LIST(ListU64)
//  ...
//  oxc::List<oxc::c::ListU64> ids(alloc);
//  if(!ids.pushBack(123, e_rr))
//      ...
//
//Lists whose elements own memory (e.g. ListCharString) can be bound with
// OXC_BIND_LIST_UNDERLYING(Name, FreeUnderlyingFunc) so the RAII free releases elements too.
//
//Only operations TList generates for *every* element type are exposed.
//The default comparator sort (ListX_sort) is opt-in per type (TListSort),
// so the wrapper exposes sortCustom (always generated) but not sort.
//createSubset is a non-owning ref view, so it is intentionally not wrapped here
// (use handle() + the C function if you need it).

namespace oxc {

	namespace c {
		#include "types/container/list.h"
		#include "types/container/list_basic_types.h"
		#include "types/base/error.h"
		#include "types/base/allocator.h"
	}

	template<typename CList>
	struct ListTraits;      //Specialized via OXC_BIND_LIST / OXC_BIND_LIST_UNDERLYING

	#define OXC_BIND_LIST_IMPL(Name, FreeFunc)                                                                          \
	template<>                                                                                                          \
	struct oxc::ListTraits<oxc::c::Name> {                                                                              \
																														\
		using Elem = oxc::c::Name##_Type;                                                                               \
																														\
		static oxc::c::Bool pushBack(oxc::c::Name &l, const Elem &t, const oxc::c::Allocator &a, oxc::c::Error *e) {    \
			return oxc::c::Name##_pushBack(&l, t, &a, e);                                                               \
		}                                                                                                               \
																														\
		static oxc::c::Bool pushFront(oxc::c::Name &l, const Elem &t, const oxc::c::Allocator &a, oxc::c::Error *e) {   \
			return oxc::c::Name##_pushFront(&l, t, &a, e);                                                              \
		}                                                                                                               \
																														\
		static oxc::c::Bool popBack(oxc::c::Name &l, Elem *out, oxc::c::Error *e) {                                     \
			return oxc::c::Name##_popBack(&l, out, e);                                                                  \
		}                                                                                                               \
																														\
		static oxc::c::Bool popFront(oxc::c::Name &l, Elem *out, oxc::c::Error *e) {                                    \
			return oxc::c::Name##_popFront(&l, out, e);                                                                 \
		}                                                                                                               \
																														\
		static oxc::c::Bool insert(                                                                                     \
			oxc::c::Name &l, oxc::c::U64 i, const Elem &t, const oxc::c::Allocator &a, oxc::c::Error *e                 \
		) {                                                                                                             \
			return oxc::c::Name##_insert(&l, i, t, &a, e);                                                              \
		}                                                                                                               \
																														\
																														\
		static oxc::c::Bool erase(oxc::c::Name &l, oxc::c::U64 i, oxc::c::Error *e) {                                   \
			return oxc::c::Name##_erase(&l, i, e);                                                                      \
		}                                                                                                               \
																														\
		static oxc::c::Bool eraseAll(                                                                                   \
			oxc::c::Name &l, const Elem &t, const oxc::c::Allocator &a, oxc::c::EqualsFunction eq, oxc::c::Error *e     \
		) {                                                                                                             \
			return oxc::c::Name##_eraseAll(&l, t, &a, eq, e);                                                           \
		}                                                                                                               \
																														\
		static oxc::c::U64 findFirst(                                                                                   \
			const oxc::c::Name &l, const Elem &t, oxc::c::U64 index, oxc::c::EqualsFunction eq                          \
		) {                                                                                                             \
			return oxc::c::Name##_findFirst(l, t, index, eq);                                                           \
		}                                                                                                               \
																														\
		static oxc::c::Bool contains(                                                                                   \
			const oxc::c::Name &l, const Elem &t, oxc::c::U64 off, oxc::c::EqualsFunction eq                            \
		) {                                                                                                             \
			return oxc::c::Name##_contains(l, t, off, eq);                                                              \
		}                                                                                                               \
																														\
		static oxc::c::Bool sortCustom(oxc::c::Name &l, oxc::c::CompareFunction func, void *context) {                  \
			return oxc::c::Name##_sortCustom(l, func, context);                                                         \
		}                                                                                                               \
																														\
		static oxc::c::Bool reverse(oxc::c::Name &l) { return oxc::c::Name##_reverse(l); }                              \
		static oxc::c::Bool swap(oxc::c::Name &l, oxc::c::U64 i, oxc::c::U64 j, oxc::c::Error *e) {                     \
			return oxc::c::Name##_swap(l, i, j, e);                                                                     \
		}                                                                                                               \
																														\
		static oxc::c::Bool eq(const oxc::c::Name &a, const oxc::c::Name &b) { return oxc::c::Name##_eq(a, b); }        \
																														\
		static oxc::c::Bool createRepeated(                                                                             \
			oxc::c::U64 len, const Elem &t, const oxc::c::Allocator &a, oxc::c::Name *result, oxc::c::Error *e          \
		) {                                                                                                             \
			return oxc::c::Name##_createRepeated(len, t, &a, result, e);                                                \
		}                                                                                                               \
																														\
		static oxc::c::Bool resize(oxc::c::Name &l, oxc::c::U64 len, const oxc::c::Allocator &a, oxc::c::Error *e) {    \
			return oxc::c::Name##_resize(&l, len, &a, e);                                                               \
		}                                                                                                               \
																														\
		static oxc::c::Bool reserve(oxc::c::Name &l, oxc::c::U64 cap, const oxc::c::Allocator &a, oxc::c::Error *e) {   \
			return oxc::c::Name##_reserve(&l, cap, &a, e);                                                              \
		}                                                                                                               \
																														\
		static oxc::c::Bool clear(oxc::c::Name &l) { return oxc::c::Name##_clear(&l, nullptr); }                        \
		static void freeList(oxc::c::Name &l, const oxc::c::Allocator &a) { FreeFunc; }                                 \
	};

	#define OXC_BIND_LIST(Name) OXC_BIND_LIST_IMPL(Name, oxc::c::Name##_free(&l, &a))

	//For lists whose elements own memory; Func must have signature void(Name*, Allocator) or
	// void(Name*, const Allocator*) like the existing ListX_freeUnderlying functions;
	//pass the exact call, e.g. OXC_BIND_LIST_UNDERLYING(ListCharString, ListCharString_freeUnderlying(&l, &a))
	#define OXC_BIND_LIST_UNDERLYING(Name, FreeCall) OXC_BIND_LIST_IMPL(Name, oxc::c::FreeCall)

	template<typename CList>
	class List {

		using Traits = ListTraits<CList>;

	public:

		using Elem = typename Traits::Elem;

		//The underlying C TList stores elements as raw bytes (memcpy) and never runs C++ ctors/dtors,
		// and the RAII free just releases the buffer.
		//A non-trivial element type would therefore leak its resources (dtor never called) or corrupt on copy,
		// so only C-style POD elements are allowed.
		static_assert(
			std::is_trivially_copyable<Elem>::value && std::is_trivially_destructible<Elem>::value,
			"oxc::List element type must be trivially copyable and trivially destructible (a C-style POD)"
		);

	private:

		//Holds a C++ comparator for the duration of one sortCustom call, see the template overload below.

		template<typename F>
		struct SortCallable {

			F func;

			//The only function of ours the C sort calls, so its signature is builtin only on purpose.
			//An ECompareResult return here would be a different type to the sort's own, which
			// -fsanitize=function reports as a call through an incorrect function type (see CompareInvoke).

			static c::I8 invoke(const void *aPtr, const void *bPtr, void *context) {
				SortCallable *self = (SortCallable*) context;
				const c::ECompareResult res = self->func(*(const Elem*) aPtr, *(const Elem*) bPtr);
				return res == c::ECompareResult_Lt ? (c::I8) -1 : (res == c::ECompareResult_Gt ? (c::I8) 1 : (c::I8) 0);
			}
		};

		CList list;
		c::Allocator alloc;

		void release() noexcept {
			Traits::freeList(list, alloc);
			list = CList{};
		}

	public:

		List(const c::Allocator &alloc) noexcept : list{}, alloc(alloc) {}
		~List() noexcept { release(); }

		List(const List&) = delete;
		List &operator=(const List&) = delete;

		List(List &&other) noexcept : list(other.list), alloc(other.alloc) {
			other.list = CList{};
		}

		List &operator=(List &&other) noexcept {

			if(this == &other)
				return *this;

			release();
			list = other.list;
			alloc = other.alloc;
			other.list = CList{};
			return *this;
		}

		//Growth / insertion

		[[nodiscard]] c::Bool pushBack(const Elem &t, c::Error *e_rr = nullptr) noexcept {
			return Traits::pushBack(list, t, alloc, e_rr);
		}

		[[nodiscard]] c::Bool pushFront(const Elem &t, c::Error *e_rr = nullptr) noexcept {
			return Traits::pushFront(list, t, alloc, e_rr);
		}

		[[nodiscard]] c::Bool insert(c::U64 index, const Elem &t, c::Error *e_rr = nullptr) noexcept {
			return Traits::insert(list, index, t, alloc, e_rr);
		}

		//Removal

		[[nodiscard]] c::Bool popBack(Elem &out, c::Error *e_rr = nullptr) noexcept {
			return Traits::popBack(list, &out, e_rr);
		}

		[[nodiscard]] c::Bool popFront(Elem &out, c::Error *e_rr = nullptr) noexcept {
			return Traits::popFront(list, &out, e_rr);
		}

		[[nodiscard]] c::Bool erase(c::U64 index, c::Error *e_rr = nullptr) noexcept {
			return Traits::erase(list, index, e_rr);
		}

		//eq nullptr = raw bytewise compare
		[[nodiscard]] c::Bool eraseAll(const Elem &t, c::Error *e_rr = nullptr, c::EqualsFunction eq = nullptr) noexcept {
			return Traits::eraseAll(list, t, alloc, eq, e_rr);
		}

		//Search (eq nullptr = raw bytewise compare)

		[[nodiscard]] c::U64 findFirst(const Elem &t, c::U64 index = 0, c::EqualsFunction eq = nullptr) const noexcept {
			return Traits::findFirst(list, t, index, eq);
		}

		[[nodiscard]] c::Bool contains(const Elem &t, c::U64 offset = 0, c::EqualsFunction eq = nullptr) const noexcept {
			return Traits::contains(list, t, offset, eq);
		}

		//Ordering (default comparator sort is per-type opt-in, so only sortCustom is exposed generically)

		//context reaches the comparator untouched, so it can carry state without a global.

		[[nodiscard]] c::Bool sortCustom(c::CompareFunction func, void *context = nullptr) noexcept {
			return Traits::sortCustom(list, func, context);
		}

		//C++ style sortCustom; the comparator is any callable taking two elements, captures included.
		//Excluded for a plain c::CompareFunction so the overload above still wins for those.
		//Nothing is allocated: a sort runs to completion before returning, so the callable lives on the stack
		// for exactly as long as the C sort needs it.

		template<typename F, typename = std::enable_if_t<!std::is_convertible<F, c::CompareFunction>::value>>
		[[nodiscard]] c::Bool sortCustom(F &&f) noexcept {

			using Callable = SortCallable<typename std::decay<F>::type>;

			Callable callable { std::forward<F>(f) };
			c::CompareWrapper wrapper { &Callable::invoke, &callable };

			//The comparator the sort receives is the C forwarder, so the function it calls was compiled with
			// the types it calls it through; only Callable::invoke crosses, and that is builtin only.

			return Traits::sortCustom(list, &c::CompareWrapper_compare, &wrapper);
		}
		[[nodiscard]] c::Bool reverse() noexcept { return Traits::reverse(list); }
		[[nodiscard]] c::Bool swap(c::U64 i, c::U64 j, c::Error *e_rr = nullptr) noexcept {
			return Traits::swap(list, i, j, e_rr);
		}

		//Sizing

		[[nodiscard]] c::Bool resize(c::U64 len, c::Error *e_rr = nullptr) noexcept {
			return Traits::resize(list, len, alloc, e_rr);
		}

		[[nodiscard]] c::Bool reserve(c::U64 cap, c::Error *e_rr = nullptr) noexcept {
			return Traits::reserve(list, cap, alloc, e_rr);
		}

		//Resets *this to a list of 'length' copies of 'value'
		[[nodiscard]] c::Bool createRepeated(c::U64 length, const Elem &value, c::Error *e_rr = nullptr) noexcept {
			release();
			return Traits::createRepeated(length, value, alloc, &list, e_rr);
		}

		void clear() noexcept { Traits::clear(list); }

		//Comparison

		[[nodiscard]] bool operator==(const List &other) const noexcept { return Traits::eq(list, other.list); }
		[[nodiscard]] bool operator!=(const List &other) const noexcept { return !Traits::eq(list, other.list); }

		//Access

		[[nodiscard]] c::U64 size() const noexcept { return list.length; }
		[[nodiscard]] bool empty() const noexcept { return !list.length; }

		[[nodiscard]] Elem &operator[](c::U64 i) noexcept { return list.ptrNonConst[i]; }
		[[nodiscard]] const Elem &operator[](c::U64 i) const noexcept { return list.ptr[i]; }

		[[nodiscard]] Elem *begin() noexcept { return list.ptrNonConst; }
		[[nodiscard]] Elem *end() noexcept { return list.ptrNonConst + list.length; }
		[[nodiscard]] const Elem *begin() const noexcept { return list.ptr; }
		[[nodiscard]] const Elem *end() const noexcept { return list.ptr + list.length; }

		//Interop with C: view or transfer ownership of the underlying C list.

		[[nodiscard]] CList &handle() noexcept { return list; }
		[[nodiscard]] const CList &handle() const noexcept { return list; }

		//Caller takes ownership; must free with the same allocator.
		[[nodiscard]] CList steal() noexcept {
			CList tmp = list;
			list = CList{};
			return tmp;
		}

		//Take ownership of a C list allocated with this wrapper's allocator.
		void adopt(CList &l) noexcept {
			release();
			list = l;
			l = CList{};
		}
	};
}
