/* OxC3(Oxsomi core 3), a general framework and toolset for cross-platform applications.
*  Copyright (C) 2023 - 2026 Oxsomi / Nielsbishere (Niels Brunekreef)
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program. If not, see https://github.com/Oxsomi/core3/blob/main/LICENSE.
*  Be aware that GPL3 requires closed source products to be GPL3 too if released to the public.
*  To prevent this a separate license will have to be requested at contact@osomi.net for a premium;
*  This is called dual licensing.
*/

//types/container/texture_format.hpp
//
//GENERATED by src/tools/generate_hpp.py from include/types/container/texture_format.h - do not edit by hand.
//Re-run the generator (or `--check` in CI) after changing the C header.

#pragma once
#include <stdbool.h>
#include <stdint.h>
#include <assert.h>

namespace oxc {

	namespace c {
		#include "types/container/texture_format.h"
	}

	//Generated wrapper around the C ETextureFormat.
	//Pure enum queries over ETextureFormat, no state.
	namespace ETextureFormat {

		[[nodiscard]] inline c::ETexturePrimitive getPrimitive(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_getPrimitive(f);
		}

		[[nodiscard]] inline c::Bool getIsCompressed(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_getIsCompressed(f);
		}

		[[nodiscard]] inline c::U64 getBits(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_getBits(f);
		}

		[[nodiscard]] inline c::U64 getAlphaBits(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_getAlphaBits(f);
		}

		[[nodiscard]] inline c::U64 getBlueBits(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_getBlueBits(f);
		}

		[[nodiscard]] inline c::U64 getGreenBits(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_getGreenBits(f);
		}

		[[nodiscard]] inline c::U64 getRedBits(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_getRedBits(f);
		}

		[[nodiscard]] inline c::Bool hasRed(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_hasRed(f);
		}

		[[nodiscard]] inline c::Bool hasGreen(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_hasGreen(f);
		}

		[[nodiscard]] inline c::Bool hasBlue(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_hasBlue(f);
		}

		[[nodiscard]] inline c::Bool hasAlpha(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_hasAlpha(f);
		}

		[[nodiscard]] inline c::U8 getChannels(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_getChannels(f);
		}

		[[nodiscard]] inline c::ETextureCompressionType getCompressionType(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_getCompressionType(f);
		}

		[[nodiscard]] inline c::ETextureCompressionAlgo getCompressionAlgo(c::ETextureFormat f) noexcept {
			return c::ETextureFormat_getCompressionAlgo(f);
		}

		[[nodiscard]] inline c::Bool getAlignment(c::ETextureFormat f, c::U8 *x, c::U8 *y) noexcept {
			return c::ETextureFormat_getAlignment(f, x, y);
		}

		[[nodiscard]] inline c::U64 getSize(c::ETextureFormat f, c::U32 w, c::U32 h, c::U32 l) noexcept {
			return c::ETextureFormat_getSize(f, w, h, l);
		}

	}
}
