/* OxC3(Oxsomi core 3), a general framework and toolset for cross-platform applications.
*  Copyright (C) 2023 - 2026 Oxsomi / Nielsbishere (Niels Brunekreef)
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program. If not, see https://github.com/Oxsomi/core3/blob/main/LICENSE.
*  Be aware that GPL3 requires closed source products to be GPL3 too if released to the public.
*  To prevent this a separate license will have to be requested at contact@osomi.net for a premium;
*  This is called dual licensing.
*/

//platforms/test/functional/test_platforms_functional_shared.h
//
//Shared state, helpers and platform shims used by every F* functional test file.
//Each test file (buffer/windowstate/input/csd) includes this header; only the
// single entrypoint .c calls setup()/shutdown() and the individual Test_* entries.

#pragma once
#include "platforms/window.h"
#include "types/math/vec2.h"
#include "types/base/types.h"

#ifdef __cplusplus
	extern "C" {
#endif

typedef struct Test Test;

//How long to hold a visual window open for human inspection
#define VISUAL_HOLD_NS  (3 * SECOND)

// -- Shared window manager, owned by the entrypoint, used by every test file --

extern WindowManager windowManager;
extern Bool windowManagerReady;

Bool Test_functionalSetup(Test *t);
void Test_functionalShutdown();

//Try to open a physical window; fall back to virtual if unavailable.
WindowRef *createWindow(
	Test *t,
	const C8 *titleStr,
	I32x2 size,
	I32x2 pos,
	EWindowHint hint,
	EWindowFormat fmt
);

//Same as createWindow but accepts a custom WindowCallbacks (e.g. onDraw).
WindowRef *createWindowCallback(
	Test *t,
	const C8 *titleStr,
	I32x2 pos,
	I32x2 size,
	EWindowHint hint,
	EWindowFormat fmt,
	WindowCallbacks cbs
);

//Ask the OS to deliver a fresh WM_PAINT / frame cycle (so onDraw runs again with
//whatever new state the test just set), then blit the result to screen.
//
//This does NOT touch the CPU buffer itself; that's the job of the window's
//onDraw callback. See the file header comment for why.
//
//On Win32 this calls InvalidateRect, since BeginPaint's clip region is only
//regenerated by an explicit invalidate or certain OS-driven events (resize with
//CS_HREDRAW/CS_VREDRAW, expose, etc) - relying solely on the latter is what made
//the old F2/F14/F18 tests flaky after a resize or toggle.
//
//On Linux/Wayland there's no separate "invalidate" step: the compositor drives
//redraws via frame callbacks during WindowManager_step, so pumping is sufficient.
void present(Test *t, Window *w);

//Same idea as present(), but without the "present" assertion and without its
//own internal pump - intended for hot loops (e.g. painting on every step of a
//drag) where calling present() per-step would both spam duplicate assertions
//and double up on pumping that the loop is already doing itself.
void presentQuiet(Window *w);

//Invalidate window's surface to force a WM_PAINT (No-op on non Windows).
void invalidateForRepaint(Window *w);

//Pump the window manager for up to `ns` nanoseconds.
void pump(Ns ns);

#ifdef __cplusplus
	}
#endif
