name: Android Vulkan
on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      name: Android Vulkan
      runner: windows-2022
      os: android
      vulkan: true
      build_flags: ''
      python_cmd: python
      setup_python: false
      python_version: ''
      hook_name: Android-Windows-static
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
