name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Windows build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: cmake build
      run: cmake -DCMAKE_BUILD_TYPE=Debug . -G "Visual Studio 17 2022" -DEnableSIMD=On
    - name: build
      run: cmake --build . -j 8
    - name: dir
      run: dir
    - name: tree
      run: tree
    - name: unit test
      run: .\bin\Debug\OxC3_test.exe
    - name: cmake build fallback
      run: cmake -DCMAKE_BUILD_TYPE=Debug . -G "Visual Studio 17 2022" -DEnableSIMD=Off
    - name: build
      run: cmake --build . -j 8
    - name: unit test
      run: .\bin\Debug\OxC3_test.exe