name: C/C++ CI

on: [push, pull_request]

jobs:
  build_windows:
    name: Windows build
    runs-on: windows-2022
    env:
      VULKAN_SDK: C:\VulkanSDK\
    steps:
    - uses: actions/checkout@v1
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        cache: true
    - name: build for fast check
      run: D:\a\core3\core3\build.bat Release On Off
    - name: build for software float fallback check
      run: D:\a\core3\core3\build.bat Release On On
    - name: build for SIMD fallback check
      run: D:\a\core3\core3\build.bat Release Off Off
    - name: build for debug check
      run: D:\a\core3\core3\build.bat Debug On Off
  build_osx:
    name: OSX build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        cache: true
    - name: build for SIMD fallback check
      run: D:\a\core3\core3\build.bat Release Off Off
    - name: build for debug check
      run: D:\a\core3\core3\build.bat Debug Off Off