name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Windows build
    runs-on: windows-2022
    env:
      VULKAN_SDK: C:\VulkanSDK\
    steps:
    - uses: actions/checkout@v1
    - name: Setup Vulkan
      run: |
          $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
          echo Version $ver
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
          echo Downloaded
          .\VulkanSDK.exe --root C:\VulkanSDK  --accept-licenses --default-answer --confirm-command install
    - name: build for fast check
      run: D:\a\core3\core3\build.bat Release On Off
    - name: build for software float fallback check
      run: D:\a\core3\core3\build.bat Release On On
    - name: build for SIMD fallback check
      run: D:\a\core3\core3\build.bat Release Off Off
    - name: build for debug check
      run: D:\a\core3\core3\build.bat Debug On Off