name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Windows build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: cmake build
      run: build.bat Debug On
    - name: cmake build
      run: build.bat Debug Off