name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Windows build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: D:\a\core3\core3\build.bat Release On On
    - name: build
      run: D:\a\core3\core3\build.bat Release Off On