name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Windows build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: dir
      run: dir
    - name: tree
      run: tree
    - name: build
      run: build Debug On
    - name: build
      run: build Debug Off