name: Linux x64 Vulkan static
on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      name: Linux x64 Vulkan static
      runner: ubuntu-latest
      os: linux
      vulkan: true
      build_flags: '-o cliGraphics=False'
      python_cmd: python3
      setup_python: false
      python_version: ''
      hook_name: Linux-x64-static
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
