name: Linux x64 Vulkan dynamic
on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      name: Linux x64 Vulkan dynamic
      runner: ubuntu-latest
      os: linux
      build_flags: '-dynamic_linking True -o cliGraphics=False'
      python_cmd: python3
      setup_python: false
      python_version: ''
      hook_name: Linux-x64-dynamic
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
