name: Linux ARM64 Vulkan dynamic
on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      name: Linux ARM64 Vulkan dynamic
      runner: ubuntu-24.04-arm
      os: linux
      vulkan: true
      build_flags: '-dynamic_linking True -o cliGraphics=False'
      python_cmd: python3
      setup_python: false
      python_version: ''
      hook_name: Linux-arm64-dynamic
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
