name: Linux Vulkan ARM64

on: [push]

jobs:
  build:
    name: Linux build arm
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        version: 1.4.309.0
        cache: true
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
    - name: Configure conan
      run: conan profile detect
    - name: Install wayland
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libwayland-dev libxkbcommon-dev
    - name: Cache Build
      uses: actions/cache@v4
      with:
        path: ~/.conan2/p
        key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/packages') }}
    - name: build for fast check
      run: python build.py -mode Release -tests True -o cliGraphics=False
    - name: build for SIMD fallback check
      run: python build.py -mode Release -simd False -tests True -o cliGraphics=False
    - name: build for debug check
      run: python build.py -mode Release -tests True -o cliGraphics=False
    - name: Delete non package files for cache
      run: rm -rf ~/.conan2/p/b/*/b
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Send Webhook Notification
      if: always()
      env:
        JOB_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        HOOK_OS_NAME: ${{ runner.os }}-arm64-static
        WORKFLOW_NAME: ${{ github.workflow }}
      run: |
        git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
        bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
      shell: bash