name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: OSX build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        cache: true
    - name: build for SIMD fallback check
      run: /Users/runner/work/core3/core3/build.sh Release Off
    - name: build for debug check
      run: /Users/runner/work/core3/core3/build.sh Debug Off
    - name: Send webhook notification
      if: always()
      env:
        JOB_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        HOOK_OS_NAME: ${{ runner.os }}
        WORKFLOW_NAME: ${{ github.workflow }}
        WEBHOOK_REPO: ${{ secrets.WEBHOOK_REPO }}
      run: |
        echo Status: $JOB_STATUS
        git clone $WEBHOOK_REPO webhook
        bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
      shell: bash