name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: OSX build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        cache: true
    - name: build for SIMD fallback check
      run: /Users/runner/work/core3/core3/build.sh Release Off Off
    - name: build for debug check
      run: /Users/runner/work/core3/core3/build.sh Debug Off Off