name: macOS x64 Vulkan static
on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      name: macOS x64 Vulkan static
      runner: macos-26
      os: macos
      vulkan: true
      build_flags: '-o cliGraphics=False'
      python_cmd: python
      setup_python: true
      python_version: '3.10'
      hook_name: macOS-x64-static
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
