name: macOS ARM64 Vulkan dynamic
on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      name: macOS ARM64 Vulkan dynamic
      runner: macos-15
      os: macos
      vulkan: true
      build_flags: '-dynamic_linking True -o cliGraphics=False'
      python_cmd: python
      setup_python: true
      python_version: '3.10'
      hook_name: macOS-arm64-dynamic
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
