name: Windows ARM64 Vulkan static
on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      name: Windows ARM64 Vulkan static
      runner: windows-11-arm
      os: windows
      vulkan: true
      build_flags: '-o forceVulkan=True -o cliGraphics=False'
      python_cmd: python
      setup_python: true
      python_version: '3.13'
      hook_name: Windows-arm64-vk-static
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
