name: Windows x64 D3D12 static
on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      name: Windows x64 D3D12 static
      runner: windows-2022
      os: windows
      vulkan: false
      build_flags: '-o cliGraphics=False'
      python_cmd: python
      setup_python: false
      python_version: ''
      hook_name: Windows-x64-d3d12-static
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
