name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Windows build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'true'
    - name: build for fast check
      run: D:\a\core3\core3\build.sh Release On -DForceVulkan=Off -DCLIGraphics=Off
    - name: build for debug check
      run: D:\a\core3\core3\build.sh Debug On -DForceVulkan=Off -DCLIGraphics=Off
    - uses: actions/setup-ruby@v1
    - name: Send Webhook Notification
      if: always()
      env:
        JOB_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        HOOK_OS_NAME: ${{ runner.os }}
        WORKFLOW_NAME: ${{ github.workflow }}
      run: |
        git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
        bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
      shell: bash