name: Windows x64 Vulkan static
on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      name: Windows x64 Vulkan static
      runner: windows-2022
      os: windows
      build_flags: '-o forceVulkan=True -o cliGraphics=False'
      python_cmd: python
      setup_python: false
      python_version: ''
      hook_name: Windows-x64-vk-static
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
