name: Windows x64 D3D12+Vulkan dynamic
on: [push]

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      name: Windows x64 D3D12+Vulkan dynamic
      runner: windows-2022
      os: windows
      vulkan: true
      build_flags: '-dynamic_linking True -o forceVulkan=True -o cliGraphics=False'
      python_cmd: python
      setup_python: false
      python_version: ''
      hook_name: Windows-x64-dynamic
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
