name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Windows build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
    - name: build for fast check
      run: conan create . -o cliGraphics=False -o enableSIMD=True -s build_type=Release
    - name: build for SIMD fallback check
      run: conan create . -o cliGraphics=False -o enableSIMD=False -s build_type=Release
    - name: build for fast check
      run: conan create . -o cliGraphics=False -o enableSIMD=True -s build_type=Debug
    - uses: actions/setup-ruby@v1
    - name: Send Webhook Notification
      if: always()
      env:
        JOB_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        HOOK_OS_NAME: ${{ runner.os }}
        WORKFLOW_NAME: ${{ github.workflow }}
      run: |
        git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
        bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
      shell: bash