# OxC3(Oxsomi core 3), a general framework and toolset for cross-platform applications.
# Copyright (C) 2023 - 2026 Oxsomi / Nielsbishere (Niels Brunekreef)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://github.com/Oxsomi/core3/blob/main/LICENSE.
# Be aware that GPL3 requires closed source products to be GPL3 too if released to the public.
# To prevent this a separate license will have to be requested at contact@osomi.net for a premium;
# This is called dual licensing.

"""Turns the built-in HLSL headers into one C translation unit.

The compiler resolves `#include "@types.hlsli"` out of its own binary rather than from disk, so those headers
have to exist as string data inside it. They used to do that by being string literals themselves: each file
started with R"( and ended with )", and compiler.cpp #included it in the middle of a declaration.

That cost twice. The files were not HLSL as far as any editor was concerned, so nothing highlighted or
checked them; and every one of them was a dependency of compiler.cpp, so editing a single header recompiled
that whole translation unit and relinked a 187MB module.

Now they are ordinary HLSL and this generates the string data beside them, in a file nothing else includes.
Editing a header rebuilds that one generated file.
"""

import argparse
import io
import os
import sys

# MSVC refuses a string literal over 16380 bytes, and two of these headers are past that, so the text is
# emitted as adjacent literals. The compiler concatenates them back into one array.

CHUNK = 4000

ESCAPES = {
	ord('\\'): '\\\\',
	ord('"'): '\\"',
	ord('\n'): '\\n',
	ord('\r'): '\\r',
	ord('\t'): '\\t',
}


def escape(data):
	"""C escaped text for one file, as a list of literal sized pieces."""

	out = []
	cur = []
	length = 0

	for byte in data:

		esc = ESCAPES.get(byte)

		if esc is None:
			# Printable ASCII goes through as itself; anything else takes a three digit octal escape, which
			# unlike \x cannot swallow a following hex digit.
			esc = chr(byte) if 0x20 <= byte < 0x7F else '\\%03o' % byte

		if length + len(esc) > CHUNK:
			out.append(''.join(cur))
			cur = []
			length = 0

		cur.append(esc)
		length += len(esc)

	out.append(''.join(cur))
	return out


def symbolFor(name):
	"""A C identifier for a header name, e.g. extension.RayReorder.hlsli -> builtIn_extension_RayReorder."""

	stem = name[:-len('.hlsli')] if name.endswith('.hlsli') else name
	return 'builtIn_' + ''.join(c if c.isalnum() else '_' for c in stem)


def main():

	parser = argparse.ArgumentParser(description="Embed the built-in HLSL headers into a C file")
	parser.add_argument("-output", required=True, help="C file to write")
	parser.add_argument("inputs", nargs="+", help="the .hlsli files")
	args = parser.parse_args()

	# Sorted so the generated file depends on the set of headers rather than on the order the caller globbed
	# them in, which keeps the output identical between machines.

	inputs = sorted(args.inputs, key=lambda p: os.path.basename(p).lower())

	lines = [
		"//Generated by src/tools/embed_hlsli.py. Edit the .hlsli files, not this.",
		"",
		"#include \"shader_compiler/compiler.h\"",
		"",
	]

	entries = []

	for path in inputs:

		name = os.path.basename(path)
		symbol = symbolFor(name)
		entries.append((name, symbol))

		with io.open(path, "rb") as f:
			data = f.read()

		lines.append("static const C8 %s[] =" % symbol)

		for piece in escape(data):
			lines.append("\t\"%s\"" % piece)

		lines.append(";")
		lines.append("")

	lines.append("const CompilerBuiltInInclude CompilerBuiltInIncludes[] = {")

	width = max(len(name) for name, _ in entries) + 3

	for name, symbol in entries:
		lines.append("\t{ %-*s %s }," % (width, '"%s",' % name, symbol))

	lines.append("};")
	lines.append("")
	lines.append("const U64 CompilerBuiltInIncludeCount =")
	lines.append("\tsizeof(CompilerBuiltInIncludes) / sizeof(CompilerBuiltInIncludes[0]);")
	lines.append("")

	text = "\n".join(lines)

	# Only rewritten when it differs, so a build that changed nothing does not recompile this or relink what
	# holds it.

	if os.path.isfile(args.output):
		with io.open(args.output, "r", newline="") as f:
			if f.read() == text:
				return 0

	with io.open(args.output, "w", newline="") as f:
		f.write(text)

	return 0


if __name__ == "__main__":
	sys.exit(main())
